### ISSUE TITLE
User Proile - Cover Image Sizing issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#105]
when a user upload bigger size image for his cover photo....the structure changes & is looking wiered 
for eg. see this http://beta.fitrangi.com/profile/abhijeet-zaware

can we fix a cover image size....as per UI...fix it to that particular BOX size

**Comment by arshadansari27** [comment]
The problem will be corrected when we add cropping fuctionality... till then @abdul can we show the profile picture in fixed aspect ratio and overflow hide the rest of the image? we need this in many place.. in fact all over the place... lets start with profile..

**Comment by 89abdul** [comment]
yes






-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --
[image: photo]
ABDUL RAZAK SHAIKH
 CREATIVE   dESIGNER
Mobile:9819992152 | Email:89abdul@gmail.com
<https://www.facebook.com/89abdul>  <https://twitter.com/89abdulrazak>
<https://www.linkedin.com/in/89abdulrazak>
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --

**Comment by 89abdul** [comment]
we have to make fixed size or add mediaquieries for every viewport screen





-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --
[image: photo]
ABDUL RAZAK SHAIKH
 CREATIVE   dESIGNER
Mobile:9819992152 | Email:89abdul@gmail.com
<https://www.facebook.com/89abdul>  <https://twitter.com/89abdulrazak>
<https://www.linkedin.com/in/89abdulrazak>
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --

**Comment by arshadansari27** [comment]
can u show how to do it... @89abdul

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
have to define a width of image & add a class for image 
for mobile screen & tablet screen have to add a css like 

@media(max-width:767px){
.classname{ width:---px;}
}
@media(max-width:480px){
.classname{ width:---px;}
}
@media(max-width:320px){
.classname{ width:---px;}
}

**Comment by arshadansari27** [comment]
@89abdul  
can this be added to my style.css file of yours in dropbox.. and I want to know if the file is at its final version.. we need to finish this work and finalize the css... let me know...

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
Error is Solved done the changes in my-style.css & uploaded in dropbox
NO html changes

**Comment by YunusDange** [comment]
@arshadansari27  @89abdul 
It perfect...although there is one problem...in Many profile images i can see the default white border line is missing from bottom part...due to which it is looking incomplete...have to fix that

for eg. see this profiles
![screenshot-2015-05-12-07 44 27](https://cloud.githubusercontent.com/assets/7126709/7579008/db58e8de-f87a-11e4-893f-482405c42453.jpg)

**Comment by arshadansari27** [comment]
@89abdul We did handle the sizing issue.. it is just the white padding that is missing... if it is a directly html level change, lemme know how to do it.. if some changes in css, then i would prefer to have it done on profile page in dropbox with changes in mystyle.css

lemme know what u think

**Comment by 89abdul** [comment]
@arshadansari27  @YunusDange 
On this Profile Pic i have seen popup on hovering there 
remove the popup from there

**Comment by 89abdul** [comment]
@arshadansari27   
can find & replace this for 

@media (min-width: 1024px)
.userprofile-banner .user-pro {
  overflow: hidden;
  width: 280px!important;
  height: 210px!important;
  margin: 0px 5px;
}

**Comment by YunusDange** [comment]
not solved yet.....check this
![screenshot-2015-05-22-22 33 54](https://cloud.githubusercontent.com/assets/7126709/7775662/c182e58a-00d2-11e5-97d3-af9fa34742e0.jpg)

**Comment by arshadansari27** [comment]
@89abdul Really need you for this.. whatever changes you made isn't reflecting.. can you look into this...

**Comment by YunusDange** [comment]
@89abdul  @arshadansari27 
There is one more problem is the final...size....what is a final size of Profile Image Thumbnail???

It should be a Box (As per the UI) Atleast 240 x 240 

Maintain this

**Comment by 89abdul** [comment]
can find & replace this for
@arshadansari27  have you added this css & remove popover from profile pic in mypage
@media (min-width: 1024px)
.userprofile-banner .user-pro {
overflow: hidden;
width: 280px!important;
height: 210px!important;
margin: 0px 5px;
}

**Comment by 89abdul** [comment]
![error-screen](https://cloud.githubusercontent.com/assets/8382087/7795850/7b50e118-02f6-11e5-9546-e1447c2cc6a3.jpg)

Check this screenshot @arshadansari27 @YunusDange

**Comment by 89abdul** [comment]
@arshadansari27 
you just remove that popover patch & i will fixed height of pic & upload the css for you also in dropbox.

**Comment by arshadansari27** [comment]
@89abdul done..

**Comment by 89abdul** [comment]
uploaded my-style.css in dropbox

**Comment by YunusDange** [comment]
@89abdul 
There is some UI issue....borders are not looking proper...make it proper

![screenshot-2015-05-26-09 10 13](https://cloud.githubusercontent.com/assets/7126709/7804910/5f048c9e-0387-11e5-9037-322c15166d19.jpg)
