### ISSUE TITLE
Advertisement Images are not linked 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#107]
the linking option is given in editing....means when you upload advertisement ..there is a option to Link it with URL.

but in actual view it is not linked ....
for eg. check sponsored advertisements here
http://beta.fitrangi.com/article/things-you-should-carry-while-going-on-a-biking-trip--quick-and-easy-list!

**Comment by arshadansari27** [comment]
It is linked now... make sure the link is present from the admin panel...
