### ISSUE TITLE
Notification Section is Missing 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#109]
We doesn't have a notification section..

there should be a thumbnail like profile thumbnail....which will act as a notification thumbnail to show all the notifications

**Comment by arshadansari27** [comment]
All the notifications will show under my streams of user.. If I also show notifications on the top like facebook, then it will slow down our server a lot. Therefore, on the top I will only show notifications + sign in red indicating there are new notifications and when user clicks on it, he will be taken to mY stream page... for now, that will be much less intensive operation on the system...

**Comment by YunusDange** [comment]
Okkz...got that
let's see how it works and what feedback we get on this from user......Keep this ticket open..we will close it afterwards

**Comment by arshadansari27** [comment]
We can reopen this later if needed
