### ISSUE TITLE
Discussion - Submitting Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#110]
Whenever a user write new discussion and click on save...the error shows "Not Authorised" 
but that Discussion get submitted (Admin can see that discussion in approval list)

After Clicking on Save button a pop-up message should come.... which should read 
"Thank you for posting a discussion. Pending Admin Approval. you will be notified once it is approved by admin"
something like this

**Comment by arshadansari27** [comment]
This will show once he clicks publish... coz save toh draft mein jayega

**Comment by YunusDange** [comment]
There is no Draft Section for users...
also while writing any discussion only 2 options are there at the end

BACK & SAVE

nothing else

**Comment by YunusDange** [comment]
I don't think it is solved...still got the same error message.

Please check by posting a discussion with normal user account

**Comment by YunusDange** [comment]
Now the error is not coming but you have not put the message which i have given to you in earlier comment... Whenever use click save 

"Thank you for posting a discussion. Pending Admin Approval. you will be notified once it is approved by admin"

following things i suggest 

1) the Button Name Should be "Submit" rather than "Save" (it will indicate user that he is submiting the discussiong..coz there is no draft for this where he can find this)

2) after Clicking Save button (to be converted into Submit button) the input mode should go & then the given message should come...coz because of the scrolling user dosn;t know what happend after clicking...so that screen should go and just the message should be seen

3) it's a bus for now ...after Clicking Save button (to be converted into Submit button) a line come as "PUBLISHED BY ADMIN " which is wrong...so remove this



"Thank you for posting a discussion. Pending Admin Approval. you will be notified once it is approved by admin"

**Comment by YunusDange** [comment]
1) ?????

2) ?????

3) ?????
