### ISSUE TITLE
Discussions - Thumbnail (Without Image)

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#112]
Most of the discussions (90%) will not have cover image or any kind of a image......so it is better to create thumbnails for discussions without images like the image attached below (Present : Should be)
![screenshot-2015-05-04-16 36 47](https://cloud.githubusercontent.com/assets/7126709/7452561/9a4aef62-f27c-11e4-9ddd-cbdc08782aee.jpg)

**Comment by arshadansari27** [comment]
@YunusDange 
Added a default discussion image.. lemme know if its ok.. if not then I will remove the default and it will become like to had shown in screen shot..

btw, nice screenshots.. these kind of things are really helpful and I wanted to appreciate them.. they take time, which is why getting it done at this rate is really awesome.. thanks again...

**Comment by YunusDange** [comment]
Happy you like the approach...:) 

i think we should remove the default image from the Thumbnail and keep it as per the screen-shot.

although keep the default image inside the discussion page as it is necessary for our structure...we will create a perfect default image later on... 

Once done Close this issues

**Comment by YunusDange** [comment]
Thumbnail images are still visible ...keep only ...content & user info...as per screen shot

**Comment by arshadansari27** [comment]
it will show image when there is an image.. it doesnt make sense to hide it
ehen there is an image.. insteading of hiding correct image we shud hurry
up on default image...

**Comment by YunusDange** [comment]
we have to keep the pattern same.....either we should hide images for all or for non.

In this case...this are discussion topics so images are not that important (90% users will not put any image for sure). this is the way many discussion platforms operate. Content/topic is whats more important here...see http://www.quora.com for eg.

it will also create a difference between Journals and discussions as there inner structure is almost same.

So i suggest...Hide Thumbnail Images for all.

**Comment by arshadansari27** [comment]
got it
