### ISSUE TITLE
Discussions - With Question Mark "?" in the title have problem

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#113]
Discussion With Question Mark "?" in the title doesn't open.. we will be having more discussions with "?" in the title....as that is a main use of this section ...so need to rectify this structure ..so that if user enter question mark "?" in the title...it should't come in url (that is a issue as you explained earlier)

**Comment by arshadansari27** [comment]
This is already solved.. could it be it is because of the old data?

**Comment by arshadansari27** [comment]
Try to edit that discussion or any content whose title is made up of  ? in the title.. the fix i put will correct old data too, but it needs to be re saved once from the admin panel...
