### ISSUE TITLE
Adventures - Uploaded but Not Visible (Not Opening)

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#117]
following are the 3 Adventures which are not opening......What is a issue?

http://www.facebook.com/l.php?u=http%3A%2F%2Fbeta.fitrangi.com%2Fadventure%2Fbungee-jumping-at-yazoo-theme-park--virar--mumbai&h=YAQEBrw1F

http://www.facebook.com/l.php?u=http%3A%2F%2Fbeta.fitrangi.com%2Fadventure%2Fhot-air-ballooning-at-jaisalmer--rajasthan&h=dAQEkoN1J

http://www.facebook.com/l.php?u=http%3A%2F%2Fbeta.fitrangi.com%2Fadventure%2Fzorbing-at-prakruthi-club-%26-resort--bangalore&h=KAQEar7rq

**Comment by arshadansari27** [comment]
Something was wrong with it... don't know but it got fixed for the first one.. I suggest make some changes and reupdate the links from slug to facebook....

**Comment by YunusDange** [comment]
Keep this open until it works...i will to do that

**Comment by YunusDange** [comment]
I am deleted it & will reupload those info page and if there is any problem then will create a new ticket
