### ISSUE TITLE
Hide Channel Name "Adventure Community"

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#119]
as we have already hide "Upcoming Trips" this single channel name doesn't convey anything for now
so Hide this channel name also.....coz when users go to any sub-menu they can come back to homepage by clicking on Fitrangi Logo..that is a standard way.

SO hide this for now , we will Unhide it once  "Upcoming Trips" channel is ON

**Comment by arshadansari27** [comment]
There is no need to hide this.. i think it looks fine as it is now.. and trust me, later adding the two things "Adventure community" as well as "Upcoming Trips" will confuse user more..

**Comment by YunusDange** [comment]
Got this feedback from many users...so i think it is creating more
confusion right now....user can handle future updates (we can use our
marketing skills for that).
so i think it is better to hide it for now.

On Sat, May 9, 2015 at 2:40 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> There is no need to hide this.. i think it looks fine as it is now.. and
> trust me, later adding the two things "Adventure community" as well as
> "Upcoming Trips" will confuse user more..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/119#issuecomment-100454342>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
