### ISSUE TITLE
Not able to Save Blogs

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#122]
i have tried to create a blog through a user profile (Not admin profile)
the blog has 8-10 images inside the article....but not able to save it...whenever i click on save button...process start and never ends 
![screenshot 2015-05-08 11 47 04](https://cloud.githubusercontent.com/assets/7126709/7531486/49e6c3b2-f578-11e4-8499-d6a70350bf47.png)

**Comment by arshadansari27** [comment]
could it be becoz the image size is huge? there is 16 mb document limit and
5 mb upload limit.. keep the size less... may be it will work... can
increase the uploaad mb till we have https connection...

**Comment by YunusDange** [comment]
just checked....the overall size of those images are 10 MB ( 15 - 20 ) Images
fine for now...but we have to increase the limit soon...as 70% users write articles with photos in our domain....specially while writing experiences images will always be more than 15

**Comment by YunusDange** [comment]
@arshadansari27 
I have tried with just 3 images (1 MB) ..still the issue is same....whenever i click on save button...process start and never ends

**Comment by arshadansari27** [comment]
lowering the priority

**Comment by YunusDange** [comment]
sure but have to solve this ASAP...so that users can start writing articles which is our main objective for now. to get user generated content. some users has submitted me articles to be uploaded due to this...okkz

**Comment by arshadansari27** [comment]
i'm looking for new way to better this in a way that will allow usage of predefined templates...

**Comment by YunusDange** [comment]
Okkz..!

**Comment by arshadansari27** [comment]
@arkath Can we see if we use a different post mechanism for just this case? Where we can use multipart-form-data in jquery ajax call to handle large content due to image? lemme know what you think....

**Comment by arkath** [comment]
that would be good , but how would we sync the order of the content if we save it in multiparts?

**Comment by arshadansari27** [comment]
@YunusDange @arkath This one requires us to send two call to the server one to save the rest of the content and get the id, next will send the data as multipart-form-data coz there's a lot to upload... I want this to be done right and so moving it to next milestone...

**Comment by YunusDange** [comment]
Got it.... No issue....if it will be done before LAUNCH...then only we can launch :)

**Comment by YunusDange** [comment]
Just one thing....When user write a blog there is only one option at the end...SAVE although it will not get submitted through this option...user need to publish it in order to submit it to admin.....it seems little confusing..

Solve this by just one step ...Add "PUBLISH" button beside SAVE...on first screen itself and if user click on that then it should be get saved & submitted directly at once......that will be more feasible

**Comment by arshadansari27** [comment]
You cannot publish without saving it first.. You see the publish button only after the it has been saved once...
after first save, you will see both, save and publish button

**Comment by YunusDange** [comment]
Yes..i got that...but i think...it will create confusion and also increases
on more step....coz once you have a button called "Write a blog" most of
them will write to publish it...we already have a barrier for them that is
admin approval.....so i think we should show both the buttons ....so user
who want to just save without publishing can save (this will be less in
numbers) ...but mostly people will prefer to publish it directly.....so
lets give them both the options directly...

**Comment by arshadansari27** [comment]
Alright... I will save and publish in case of first time publish call,
without any save..
