### ISSUE TITLE
Homepage Slide Image Content Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#123]
As soon as you resize the screen - image content  --- fitrangi.com in number ---- go down & become invisible being same white color. also it create a white patch (check in mobile devide)

can we hide this "fitrangi.com in number" section  in small devises ?

**Comment by arshadansari27** [comment]
ok... we can do that

**Comment by YunusDange** [comment]
Cool....keep it on priority as got this feedback from many users and also
logically it needs to corrected :)

On Fri, May 8, 2015 at 1:13 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> ok... we can do that
>
> On Fri, May 8, 2015, 12:33 Yunus Dange <notifications@github.com> wrote:
>
> > As soon as you resize the screen - image content --- fitrangi.com in
> > number ---- go down & become invisible being same white color. also it
> > create a white patch (check in mobile devide)
> >
> > can we hide this "fitrangi.com in number" section in small devises ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/arshadansari27/fitranginew/issues/123>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/123#issuecomment-100137084>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
need @89abdul
