### ISSUE TITLE
Load More button in all sections - keep bottom margin for it 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#128]
load more button in all sections => keep bottom margin for it  ...so that it will look proper

**Comment by arshadansari27** [comment]
a little more details pls... i didnt understand...

**Comment by YunusDange** [comment]
Means give some space from bottom....Load button in all the sections are connected with footer...there is no gap..so give little gap between footer and Load button....little margin..

i can see the margin in Discussions area (when Load button shows)...for eg. http://fitrangi.com/community/discussion

Do this for other areas as well

**Comment by arshadansari27** [comment]
got it...
