### ISSUE TITLE
Flag users as not ok

### ISSUE THREAD

**Issue by arshadansari27** [arshadansari27/fitranginew#129]
A way to flag users as not ok... admin will take the call...

**Comment by YunusDange** [comment]
What exactly it means..?

**Comment by arshadansari27** [comment]
just saw a profile with user name bhosda@terimaka.com :)

we may not be able to keep.track.of alll users. so we shud make it possible
for other users to tell us which profile they have come across that is like
that..

**Comment by YunusDange** [comment]
yes right!

i have deleted it that time....but not possible to track it always

is there any solution for it??

On Sun, May 10, 2015 at 1:26 AM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> just saw a profile with user name bhosda@terimaka.com :)
>
> we may not be able to keep.track.of alll users. so we shud make it possible
> for other users to tell us which profile they have come across that is like
> that..
>
> On Sun, May 10, 2015, 00:30 Yunus Dange <notifications@github.com> wrote:
>
> > What exactly it means..?
> > On 10-May-2015 12:25 AM, "Mohammed Arshad Ansari" <
> > notifications@github.com>
> > wrote:
> >
> > > A way to flag users as not ok... admin will take the call...
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/arshadansari27/fitranginew/issues/129>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/arshadansari27/fitranginew/issues/129#issuecomment-100530135
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/129#issuecomment-100538923>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
solution is to add option like "not ok/report" button... it works like vote up or down.. once any content is flagged so, it will be shown in Approval category with Flagged option... we will take a call to delete it or leave it be.   this will work not just for profile, but also content and posts...

**Comment by YunusDange** [comment]
Cool...i think it will work....lets do this!

**Comment by YunusDange** [comment]
I think Journal Articles and Discussion sections ....doesn't need this facility...coz we already have Admin approval thing there..means...every content will go through us

for no it only requires in Finder (Profile) Section.....as we don't have any control there  

what say?

**Comment by arshadansari27** [comment]
it is needed... for users to voice the opnion abt the content... sometimes
we will approve something but users wont... this is their view of what they
see...

**Comment by YunusDange** [comment]
Okkz..got this
