### ISSUE TITLE
My Stream - Can't Edit or Delete My Posts

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#131]
I can't edit or delete post once it is get published

**Comment by arshadansari27** [comment]
Cannot edit the streams... 
only delete..
if there is any mistake, one can use the comment feature under the post...
as for the other stream.. it is generated.. so cannot be edited..only deleted...

**Comment by YunusDange** [comment]
Okkz...but i don't see any DELETE option also
