### ISSUE TITLE
Adventures Thumbnails - Bugs & Enhancement

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#134]
1) "Check" and "Star" Icon do not have any "title<- html tag" for it...like whenever user bring cursor on this icon's then the mousover text should come to tell the use about those icons. like for "Check" = Done This & "Start"= Add to Wishlist

2) Adventures which are not reviewed should have some positive term to describe it Replace word "Not reviewed yet" with "Write a review" 
and whenever there is any review..then number counting will be ok..like 1 review, 2 review etc

3) Images looked little stretched on thumbnails...can we do anything for this..?

**Comment by arshadansari27** [comment]
I and @89abdul tried solving the point no. 3.. Wasn't happening... still figuring out...

**Comment by YunusDange** [comment]
Okkz ....try,,try till you succeed :)

**Comment by YunusDange** [comment]
Point No. 1 
Icon's were perfect, i was talking about on mouse over text ....like if a user place a mouse on any icon ..there should be some mouse over text which should tell what it is ... like "Done This" for first icon and "Add to Wishlist" for second icon

Now it is looking more crowded and even you have used short form which is not required.

**Comment by arshadansari27** [comment]
Problem is on mouse over is not working.. i tried that first... wen it
didnt work i chose this.. again we will need abdul to correct the mouse
over thing

**Comment by YunusDange** [comment]
Okkz

**Comment by arshadansari27** [comment]
@89abdul any inputs? I'm using bootstrap hover (popover) to display it.. We can bypass it completely if you have something better in mind....

**Comment by YunusDange** [comment]
Don't change the Mouse Over Content....keep to similar to inner content

"Done This" & "Add to Wishlist"

no need to use "Add to Accomplished" ... everything should be in sink..in content as well

**Comment by arshadansari27** [comment]
what is missing? why was this reopened?

**Comment by YunusDange** [comment]
Read my last comment on this

**Comment by arshadansari27** [comment]
that comment didn't come on email.... so I replied that way.... got it...
