### ISSUE TITLE
Homepage - Testimonials - Can we Slider?

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#137]
right now we can't control which testimonial come first and which come last...also users will not understand how many testimonials we have..if he want to read all....so can we have a slider kind of a thing on present structure...so that we can control above things .

eg. like below
![screenshot-2015-05-11-15 33 13](https://cloud.githubusercontent.com/assets/7126709/7562613/648dc120-f7f3-11e4-9dfa-fb3fab377d70.jpg)

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
added testimonials.html page in dropbox check 
owl.carousel.min.js & owl.carousel.css is used

**Comment by 89abdul** [comment]
@arshadansari27 
Testimonials is uploaded in Dropbox 
check testimonials.html page
owl.carousel.js & owl.carousel.css is used
some Jquery in footer check that also

**Comment by YunusDange** [comment]
@arshadansari27  @89abdul 
can we have ARROWS on both the side (as shown in the above image)....as this are testimonials & people may want to read it completely ...so they can handle it...
also we want to keep selected testimonials on first view....so we can do that as well...?

let me know

**Comment by YunusDange** [comment]
I think....people can read it by handling it's animation through mouse.....Looking good and something new .. DONE for now
