### ISSUE TITLE
Login & Signup Icons - Before and after Login

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#138]
@arshadansari27  @89abdul 

Before Login
![business-profile](https://cloud.githubusercontent.com/assets/7126709/7569877/9620c44a-f829-11e4-8e28-a98d09c98b8f.jpg)

After Login
![business-profile-with-login](https://cloud.githubusercontent.com/assets/7126709/7569883/a14ca8c0-f829-11e4-9d46-86e8d7eaee2d.jpg)

Also Updated in Dropbox

**Comment by arshadansari27** [comment]
create business profile shud be seen after login

**Comment by YunusDange** [comment]
I think users will get confuse if both are side by side...we are putting
"create business profile" button there just so that business people can see
this option....that's why kept it away from regular and fix icons

**Comment by YunusDange** [comment]
Looking good 

1) but when your go to Login & Register Page.....Header is missing....make it visible

2) Give bottom Margin to Login & Register box as per the UI created by Abdul....(A space between Footer and Login & Register box)

**Comment by arshadansari27** [comment]
point no. 2 is ok...

point no. 1 is not... putting header there makes it look wierd... i was
trying that earlier... didnt look good... firstly the html that @89abdul
used is not the same as out current header... so it looks different with
this look...

on my pc without header looks better... can we finalize on this?

**Comment by YunusDange** [comment]
Point no 1
Okkz...fine with it.. we can keep this as it is for now....let c if we get any feedbacks on this in future 

Point 2 & 3 need to corrected :)

**Comment by arshadansari27** [comment]
what is point 3

**Comment by YunusDange** [comment]
After Logged In ..............2 notification Icon's look weired with the new login and members link...
can we match it like ...reducing the size of those icons and keeping in the same line as shown below...for eg.

See image attached
![c11f6a84-f879-11e4-8afa-3063327d522e](https://cloud.githubusercontent.com/assets/7126709/7582774/7d074850-f8ae-11e4-8a1d-72c4aaf58d83.jpg)

Correct Sizing should be like this

![c11f6a84-f879-11e4-8afa-3063327d522e](https://cloud.githubusercontent.com/assets/7126709/7582797/a11c8638-f8ae-11e4-93df-c7484589f90a.jpg)

**Comment by arshadansari27** [comment]
The reason it is done like this is because I can't do what you want.. even I want that.. will need @89abdul 's help here... so waiting on him

**Comment by arshadansari27** [comment]
@89 abdul.. can u fix this by saving the page as from the site and showing me what to change?

**Comment by 89abdul** [comment]
Remove class navbar-right in <ul> from navbar reg login button is there
& find navbar-right in my.css 
you will find these css 

@media (min-width: 768px)
.navbar-right {
  float: right!important;
  margin-right: 0;
}

then add these  padding: 15px 0; 
So finally it will be like these 

@media (min-width: 768px)
.navbar-right {
  float: right!important;
  margin-right: 0;
padding: 15px 0; 
}


IMPORTANT : Don't  Remove class navbar-right from icon <ul> 
If having any problem let me know

**Comment by arshadansari27** [comment]
@89abdul everything u wrote there seemed difficult :) 
if i directly change mystyle.css in dropbox, i don't know what all repercussions it will lead to... 

can you do this change (not as a general class, but as a special case class) and reflect it on the new-index.html file? I will simply overwrite the css and use the classes you will put in html....

**Comment by YunusDange** [comment]
Don't change the Mouse Over Content....keep to similar to inner content

"Done This" & "Add to Wishlist"

no need to use "Add to Accomplished" ... everything should be in sink..in content as well
