### ISSUE TITLE
Footer - Background Color Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#142]
Whenever you open the website in Mobile & Ipad devices the footer color changes to white (means Gray color area becomes white color)

check this by manually adjusting your web browser size
![screenshot-2015-05-12-13 10 25](https://cloud.githubusercontent.com/assets/7126709/7582147/75962a74-f8a8-11e4-9bec-4f5a469e0566.jpg)

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 

Where class footer is mentioned 
there is only class="col-lg-12 footer" is mentioned 

add this class col-md-12 col-sm-12 col-xs-12 

so final it will look like this 
class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer"

**Comment by arshadansari27** [comment]
done..
