### ISSUE TITLE
TAB ICON's - from Awesome Library 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#143]
Hi Arshad,
As suggested i have gone through Awesome Icon Libray and selected following icons for our TAB's 
i have tried to include all the possible TAB's we have from all sections and created a consolidated Table indicating the sutaible Icon for that TAB
Please do the needful

Procedure:
1) Visit : http://fortawesome.github.io/Font-Awesome/icons/
2) In Search bar Copy-Paste any name from column 2 to get the associated ICON
3) In case of getting more than one result through search then use column 3 name to get exact ICON's

![screenshot-2015-05-12-20 00 25](https://cloud.githubusercontent.com/assets/7126709/7589685/ab4d938a-f8e1-11e4-8ff3-71ebb03a3db2.jpg)

COLUMN 1 : COLUMN 2 :     COLUMN 3
Tab Names :  Icon Names :  Icon Sub name                                                                                          
		
My Stream : Spinner : fa-spinner
Adventure Done : flag : fa-flag
My Wish list : list : fa-list
Following : group : fa-users
Followers : group : fa-users
Journals : book :  fa-book
Discussions : File-text : fa-file-text
Photos/Videos : camera : fa-camera                                   
Favourited By : group : fa-users
How to reach : road	: fa-road
Nearby Facilities : arrows : fa-arrows
About & Reviews : star : fa-star
Top Blogs : certificate : fa-certificate
My Blogs  : pencil-square-o : fa-pencil-square-o
Latest : refresh : fa-refresh
Featured : bolt	: fa-bolt

Call me if there is any confusion :)

**Comment by 89abdul** [comment]
Yes
Fontawesome.css & fonts is included already in site folder
you just have to add a class name written above so class will be look like these

class="fa fa-arrows"

**Comment by YunusDange** [comment]
@arshadansari27  @89abdul 

I can find 3 places the icons should be replaced

1) Activity 
Second Tab "Adventures" (use following icon so that it will go in sink with all the tabs related to it)
use
Adventure Done(ADVENTURES) : flag : fa-flag

2) Adventures
Main Page Icon's as well as Thumbnails 
"DONE THIS" & "ADD TO WISHLIST" (we need to match the icons with it's main section (as it come in users TAB)  so that it will look sink)
use
Adventure Done (DONE THIS) : flag : fa-flag
My Wish list (ADD TO WISHLIST) : list : fa-list

Use it on both Main Page as well as Thumbnails 

3) In All the Sections "SECOND TAB" have some " ' " line (Dot line) above the Icon....it looks odd
Can we remove it to make it perfect
