### ISSUE TITLE
Change Button 

### ISSUE THREAD

**Issue by 89abdul** [arshadansari27/fitranginew#146]
@arshadansari27 @YunusDange 
Change design of Login,  Resigtration & All Members Button from header that looks bad in header

**Comment by YunusDange** [comment]
Yes,,,,right Abdul.

Is this looking got?? Or can you suggest something...which may be available in default gallery & goes as per our theme

![before login](https://cloud.githubusercontent.com/assets/7126709/7647922/afe3d12e-faf9-11e4-89a9-55b1caa4aa03.jpg)

**Comment by 89abdul** [comment]
@YunusDange 
i'll make it & upload in dropbox.

**Comment by YunusDange** [comment]
Cool!

On Fri, May 15, 2015 at 1:29 PM, Abdul Razak Shaikh <
notifications@github.com> wrote:

> @YunusDange <https://github.com/YunusDange>
> i'll make it & upload in dropbox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/146#issuecomment-102519328>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
Button Changes Done uploaded in dropbox
check new-index.html & get the button from the html
& my-style.css

you can also do on beta.fitrangi.com itself by adding that css created in my-style.css & add 
class="btn-head"

**Comment by YunusDange** [comment]
@89abdul 

It's not looking good at all...blue color outline doesn't look good ....also the positioning should be different

i have given you the following view...but it is completely different ...can you please try to match it with below...
- No need for any icon's with words....just match it with below...as it is..
- Keep "Create Business Profile" as per the below UI
![before-login](https://cloud.githubusercontent.com/assets/7126709/7669706/93b3dd62-fc9f-11e4-8c90-1df43990efd9.jpg)

**Comment by 89abdul** [comment]
Done changes have a look in dropbox
