### ISSUE TITLE
Use Smooth Scroll

### ISSUE THREAD

**Issue by 89abdul** [arshadansari27/fitranginew#147]
@YunusDange  @arshadansari27 
Add Smooth Scroll in Whole Website
& Scroll to Top Arrow also.

Its a simple thing just have to add a js file.

**Comment by arshadansari27** [comment]
@89abdul How about helping with that.. :)

**Comment by 89abdul** [comment]
user can see website smoothly

**Comment by arshadansari27** [comment]
is this resolved? @89abdul
