### ISSUE TITLE
Search Bar - Issues

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#148]
1)	There is no Standard or Default Search bar on website…Place a Default Search bar on Header as per UI (PSD)
2)	No Search bar is working... like Search bar in Finder, Journals, Discussions...Make it work

**Comment by arshadansari27** [comment]
we cant have main search bar... its difficult to manage from context
perspective... so removed it.. create individual issues for each search
filtering not working and assign it to me

**Comment by YunusDange** [comment]
Got it

closing this and creating individual issues for other search filters
