### ISSUE TITLE
Location & Filtering

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#149]
As we discussed over phone....we have to make both this things to work in sink..
it is very important..

**Comment by YunusDange** [comment]
Is it solved...??
Let me know the final structure ....i can't see it is getting filter by only Selecting state

**Comment by arshadansari27** [comment]
right now it shows near in 100 kms... its not state dependent...but in
thinking of a way to do the state thing.. create that part as separate
ticket... and think of it as enhancemebt once bugs r over...

**Comment by YunusDange** [comment]
Okkz ..got that....will create a separate ticket for this.....but don't take it as a enhancement....it is a bug..coz this is the offering from fitrangi...once we list business profile......the state , city filtering is what matter most for user .
