### ISSUE TITLE
Facebook & Twitter Login option 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#15]
Login With Facebook & Login With Twitter option

**Comment by YunusDange** [comment]
Hello Team,
We have to introduce Facebook & Google + Login as soon as possible ( will not have twitter login , instead that Google+ login will be there) . will facebook login all it's facilities should be there like automatic capturing of Profile picture from facebook to fitrangi profile etc

**Comment by arshadansari27** [comment]
I am not doing twitter login, only twitter sharing will be there.. Coz twitter doesn't give us email address, so we cannot capitalize on it. We currently have facebook and google login...
