### ISSUE TITLE
Admin - Creating New Adventure Page Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#152]
After Login as Admin

Administration > Adventure >Create

Whenever i try to create new info (Adventure) page ..OR try to edit old info(Adventure) page . following error shows:

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by arshadansari27** [comment]
was data error... fixed the data... test it.. i'm closing.. reopen if not fixed...
