### ISSUE TITLE
User Profile Page - Content Line Change ?

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#154]
Why "Favorite Activities" changes to "FIND YOUR FAVORITE ACTIVITIES"?????? 
![screenshot-2015-05-21-13 46 29](https://cloud.githubusercontent.com/assets/7126709/7744320/f0be6d1a-ffbf-11e4-991a-109c1eedca3d.jpg)

**Comment by arshadansari27** [comment]
it was suppose to be when there are no favorite activities selected by
user.. who general ho haya galti se... will fix it

**Comment by YunusDange** [comment]
Okk....
In that case also the line should be "Add Your Favorite Activities"
replace the word "Find" with "Add"
coz it is a user profile....he can anyway search about activities...but in this section his favorite activities will be shown to OTHERS as a part of his profile

**Comment by YunusDange** [comment]
Nothing changes.
Instead new issue created.

Now i still see the word "Find Your Favorite Activities" on My Page but when i visit others profile...even that name gets invisible...and only icon's are visible

**Comment by YunusDange** [comment]
User who have not Favorited any activity yet still have a heading "Find Your Favorite Activities" 

It should be "Add Your Favorite Activities"

**Comment by arshadansari27** [comment]
k
