### ISSUE TITLE
Filtering User Experience Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#157]
One Critical Feedback i got is....User experience issue while using any filter

Like for eg. goto "Finder" & try to use any filter (give any filtering condition) and press "Go" button.... due to our UI structure many time user don't know whether content get filtered or not directly....they has to go down to see the result...which is not user friendly..

we need to do something about it..

One solution comes to my mind is.....create a structure whenever user click on "Go" button in any section the view should shift towards the main content...showing the result to users

Call me if you don't understand this...will explain

**Comment by arshadansari27** [comment]
understood and makes sense... will do
