### ISSUE TITLE
State wise Filtering Structure - Parent & child functionality 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#158]
Like we have discussed..state wise filtering which we should enable...

but it is not just a state wise filtering thing that matter here...coz entire Parent & Child Functionality Should work overall

for example (let's take a extreme example as below)
Let's assume...a user selected his location as "Kashimira, Mira Road, Maharashtra, India" (it's my location)
Now this user profile should come in the following filtering condition

1) Mira Road (City)
2) Maharashtra (State)
3) India (Country)

Let me know if you need explanation

**Comment by YunusDange** [comment]
I don't think...it's working...please check..

Just go to Finder and search with state "Maharashtra" in location filter...and there is no result...although we have good number of users from Mumbai & Pune (who should come in result)

**Comment by arshadansari27** [comment]
Oh sorry, I thought I only had to implement it for adventures now.  I will do that for finder too.

**Comment by YunusDange** [comment]
Still not working....

Do the same thing

Just go to Finder and search with state "Maharashtra" in location filter...and there is no result...although we have good number of users from Mumbai & Pune (who should come in result)

**Comment by arshadansari27** [comment]
lemme check this

**Comment by arshadansari27** [comment]
The problem is that its working but the radius for search in case of state starts from center and the default radius is smaller than where the guys are from mumbai... so they are not shown... there's a solution to this.... 

1) Enter geo code polygon data for each country, state and city to show nearby thing
2) Update the location information to also store city, state and city, which is easier.. but requires backend change as well as update of data.. so let me think this through..

**Comment by arshadansari27** [comment]
I have fixed this issue, with second option.. However, there is some work to be done from admin panel...

We need to update the address of all the users who have already given the address from admin panel...
Basically, reset the location to same location, only this time, it will store extra information in the background.. the changes to be done shall happen after next release, which will happen after this ticket is closed automatically by the changes for fix..

**Comment by YunusDange** [comment]
Not understand it clearly....can you explain...how exactly this function will work?
