### ISSUE TITLE
Activity & My Page (Discussion TAB) - View Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#159]
the issue is same like #153 

the location is different....

1)  Activity (Discussions TAB)
eg. http://fitrangi.com/explore/activity?name=Trekking%20and%20Hiking

2) My Page (Discussions TAB)
http://fitrangi.com/community/my

**Comment by arshadansari27** [comment]
@YunusDange didn't understand... sencondly the second link is not visible from any place.. there is not way to go to that page.. how did you get there?

**Comment by arshadansari27** [comment]
![local-img](https://cloud.githubusercontent.com/assets/423442/7768751/da8529a8-009b-11e5-90c6-3f00bd09bdc6.png)
Works on my local.. unable to debug this at the moment.. let me investigate further

**Comment by YunusDange** [comment]
![screenshot-2015-05-22-16 29 46](https://cloud.githubusercontent.com/assets/7126709/7769278/e9c3f9fe-009f-11e5-85af-5ba93a116afd.jpg)

not working in my case :)

About that Community page...i forgot to tell that..there are many times....when i click My Page "Without Login" then this old community page comes....not everytime..but sometime...i think you should remove it completely..so that it should not come..even accidentally

**Comment by arshadansari27** [comment]
I will remove that completely ....
as for this problem.. let me find out what is really causing it...

I think its fixed now... take a look

**Comment by YunusDange** [comment]
Okkz...it's done now
