### ISSUE TITLE
User Profile - URL Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#163]
Got this input from lot's of users that.....If it's My profile then the URL should also show that....
so that i can even use thing in my social media links....in future..
for eg. 
facebook.com/yunus
twitter.com/yunus

similarly it should be 
fitrangi.com/yunus

then only it will look my profile

URL : http://www.fitrangi.com/community/my 
Does not Look Mine…  no personalization, also why community in url??

IT MAKE SENSE

**Comment by YunusDange** [comment]
Just a query.....
right now it is like
http://fitrangi.com/profile/samir-lalani

can it be possible to make it like
http://fitrangi.com/samir-lalani

it has tones of advantage if we can make there URL like this (which is the case in most of the social site website) the biggest will be like
1) we can market it like."Create your adventure Profile"
2) in terms of B2B companies who dosen't have a website (many in our domain) can use this as there web address 

etc..

**Comment by arshadansari27** [comment]
that is an entirely separate problem.. so ticket shudnt be reopened for
that.. and.rught now.ot isnt possible to do that right away... need to
consider that properly... lets hold on to that thought...

fixed #163
