### ISSUE TITLE
User Profile - FAVOURITE ACTIVITIES linking issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#164]
Why this Favorite Activity links take me to On Same page? 
 it should link to The activity page attached to it..

![screenshot-2015-05-22-17 23 20](https://cloud.githubusercontent.com/assets/7126709/7770026/5f95eaa0-00a7-11e5-869c-ccf891aaad7f.jpg)

**Comment by arshadansari27** [comment]
Good you made a ticket for this... I was about to fix it anyways.. :)
