### ISSUE TITLE
Guidance Text Box in - all Sections

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#167]
Whenever some section is empty there should be a Guidance text box...which should tell users that it is emtpy and what should he do to add something to this section.

for eg. Let's take My Page (TAB's)

for a first time users all his TAB's will be empty and whenever he click on those TAB's , it show nothing...not even a word "EMPTY"....although there should be a text box which should guide user for some Action.
like 
Adventure Done, Followers, Following TAB has NOThing (for initial user) not even Suggestions…. Nothing user can do here if there is no guidance… ?

Let me kno what you think?? it's a feedback from a UX guy

**Comment by arshadansari27** [comment]
I have added this and you will see it in few minutes.. I have only done this for the users on 'My Page'.. Just go through the text and suggest replacement...

**Comment by YunusDange** [comment]
I think it is looking perfect for now (the text)...
the only thing is... can we linked the section with which user need to interact as per the message
for eg.

When User goes in "Adventures Done" Tab then message is

"Mark adventures as done to see them here. Create your adventure portfolio for the rest of the world to see!"

Here attached the word "adventure" with that section link .................which is "http://fitrangi.com/explore/adventure"

same for others..so that it will create a direct action

**Comment by arshadansari27** [comment]
cool
