### ISSUE TITLE
Adventures - Thumbnail Image Content Linking 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#171]
![screenshot-2015-05-23-12 50 35](https://cloud.githubusercontent.com/assets/7126709/7782891/6fb72252-014a-11e5-9581-93a2c06fbccb.jpg)

"Write review" or when it will show count like "2 Review" etc ..it should be click-able and it should take user inside the info page at Review writing area

**Comment by arshadansari27** [comment]
got it...
