### ISSUE TITLE
Search / Filter Result - No Feedback Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#173]
Search doesn't Give ANY feedback, as result found Or not…

Means while using search or Filter option....if there is no result then that screen should show some text like..."No result Found" or something like that.....coz right now it just become blank...which create confusion whether its working or not etc....Communication is Key.....website should talk with Users

**Comment by arshadansari27** [comment]
I can add message, but then it will be common to all the list that come empty... which is why i kept it so... Also, the ajax loader can be shown to say if its completed or not....

**Comment by YunusDange** [comment]
I think same message will also work for now....it is better than keeping it blank which make user to think otherwise

**Comment by arshadansari27** [comment]
got it...
