### ISSUE TITLE
My Page - "Fitrangi.com Popular Stream Feeds" linking issues

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#176]
"Fitrangi.com Popular Stream Feeds" has nothing Clickable… how do I go to the User Or how do I view the item in the feed ?

![screenshot-2015-05-23-14 02 28](https://cloud.githubusercontent.com/assets/7126709/7783141/8303561e-0154-11e5-8b5e-1ca78008626e.jpg)

Even in Users Main stream the profile links and images are not linked

**Comment by arshadansari27** [comment]
how do i link the images? They are from the user streams of featured profiles.... Only think I can do is to take them to the stream of the user who put that post... i can't take the user to exact post, since there are not detail views for post at the moment...

**Comment by YunusDange** [comment]
Got it..

i think atleast user profile can link..so that user can visit the user profile
