### ISSUE TITLE
Website Speed & Loading Time

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#177]
This is one of the critical area we need to improve ...right now we have 14.56 seconds Avg. Page Load Time (sec)

Also there are lot's of option for which entire page loads..While saving any info at any section.. the entire page refreshes completely . ..need to make it more real-time....we need to find solution for this

**Comment by arshadansari27** [comment]
For part 1, solution is to use CDN and/or increase the number of servers (in respective order)... Everything on our side that can be done has been done on code level stuff.. So its CDN thing that we need to consider for now...

For part 2, I need a week's time to fix all the places where the page loads entirely and should be done instead in real time... One thing to do now would be to list all the critical ones that would be better to have sooner than the rest.. However this would be a separate ticket with list of those actions....

**Comment by YunusDange** [comment]
1) We need to figure out the cost...i think we will go ahead with it..come with basic idea of cost tomorrow
2) Should i create a separate ticket listing all those things which should have a real time functionality??

**Comment by arshadansari27** [comment]
for 1) I can't come up with short notice... I will try to get rough figure but not final ones....
and 2) Yes... 

In fact both these tasks can be two separate tickets for post launch milestone.... closing this one
