### ISSUE TITLE
Social Sharing Icon's should Change - Journal & Discussions 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#179]
![screenshot-2015-05-23-16 31 27](https://cloud.githubusercontent.com/assets/7126709/7783718/5139e3f4-0169-11e5-9591-d0909f375d11.jpg)

Got lot of complaints about this...this icon's dosen't looks like sharing icons....most of the users think this is our social media links....but then why we shows them on article....after clciking they understand ...it is a sharing buttons....we need to change this to something which is more understandable...like below

![screenshot-2015-05-23-16 29 38](https://cloud.githubusercontent.com/assets/7126709/7783724/8cc390dc-0169-11e5-89da-bf15ad6ab44a.jpg)

**Comment by arshadansari27** [comment]
I'm using a library to do this.. which is why it was done so quickly.. I don't know how long will I take to change the icons... Should this be critical?

**Comment by YunusDange** [comment]
I think it is important...so that users can share...which will help us to get more audience in initial phase....but you can keep it last...coz it is not a bug......but a enhancement
