### ISSUE TITLE
Call Regarding section called “My Posts” in every users account.

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#18]
We have section called “My Posts” in every users account, so either we should activate that or keep it off till we start that feature (if we activate that then approval procedure should be there, same as discussed for Forum)

**Comment by YunusDange** [comment]
Time to Activate This....we are keen to invite people for writing on fitrangi.com

**Comment by YunusDange** [comment]
Time to Activate This....we are keen to invite people for writing on Fitrangi.com

**Comment by arshadansari27** [comment]
The Blog is already added in the new admin. Now its time to bring it to the menu. Should it be between article and finder? 

Also, there are some profile related changes that are needed to be done.

**Comment by YunusDange** [comment]
Yes...between article and finder

**Comment by arshadansari27** [comment]
Closing this, as blogs have already been added. Will track blogs seperately
