### ISSUE TITLE
Email Database Access and Mailing Facility

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#180]
As we will be launching the website soon....we need to ON the communication with all the users of the website....How to go ahead about this...?
Is there any inbuilt solution to manage emails to all the users..? even Paid will work?
Or else if i can have a direct access to email database i can create a other structure from where i can handle this

let me know

**Comment by arshadansari27** [comment]
I had a plan for this.. was thinking of generating a csv file from admin panel for you to download and send  emails to.. later we can add the whole email functionality from admin panel itself and create templates to send on some frequency basis

**Comment by YunusDange** [comment]
Cool.....this should be more clear before going for Launch!

**Comment by arshadansari27** [comment]
I have added the link to the admin panel on top right to download the csv file. Let's leave it at this for now... csv files can be directly used with mail merge to send emails out....We will create a separate ticket to send email from admin panel later....
