### ISSUE TITLE
Website Speed Improvement

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#182]
Solution is to use CDN and/or increase the number of servers (in respective order)... Everything on our side that can be done has been done on code level stuff.. So its CDN thing that we need to consider for now...

**Comment by arshadansari27** [comment]
We have amazon cloudfront as cdn which was freely available till our instance is freely available to us.. so after the completion of a year of the account we created, this too will become paid.. but this is worth it..
