### ISSUE TITLE
Website URL's Structure - Make it proper

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#186]
we have to make the URL structure proper
changes like below

Homepage
OLD : http://www.fitrangi.com/explore
NEW: http://www.fitrangi.com

Activities
OLD : http://fitrangi.com/explore/activity?name=Trekking%20and%20Hiking
NEW: http://fitrangi.com/Activity/Trekking-and-Hiking

Adventures
OLD : http://fitrangi.com/explore/adventure
NEW: http://fitrangi.com/adventure

Finder
OLD : http://fitrangi.com/community/profile
NEW: http://fitrangi.com/finder

Journals
OLD : http://fitrangi.com/explore/journal
NEW: http://fitrangi.com/journal

Discussions
OLD : http://fitrangi.com/community/discussion
NEW: http://fitrangi.com/discussion

Initiatives
OLD : http://fitrangi.com/community/event
NEW: http://fitrangi.com/initiative

My Page
OLD : http://fitrangi.com/profile/yuni-fitrangi
NEW: http://fitrangi.com/yuni-fitrangi

This are the main URL's

**Comment by arshadansari27** [comment]
The last url for profile will not change.. its not possible at the moment.. except for that, I can get others done...

**Comment by YunusDange** [comment]
Cool....so change others and close thing ticket.....as we already have a separate ticket for that Last URL...that can be done after the launch....
