### ISSUE TITLE
Navigation Text Change

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#188]
i think you have missed to replace some text given in the navigation text file i have uploaded in the dropbox 
Dropbox\Shared Fitrangi\Nevigation Content & Images

So what i have done is... i have created a color coding in that file itself & the text in RED color need to be replaced with present website navigation content....not much just 4-5 text is there.....Please check and close this once that is done

**Comment by arshadansari27** [comment]
I changed all the text.. which ones are missed?

**Comment by YunusDange** [comment]
just things missed this time

1) Homepage : replace
" fitrangi.com in number "
with
" Be Adventurous Be Fitrangi "

2) Homepage : Make "A" capital 
Choose your Activity


as far as content changes are concern...try to replace it as it is....as those changes always comes from Sandeep or Deepali Mam....to make it grammatically as well as presentation wise perfect

**Comment by YunusDange** [comment]
Bhai 
Choose your Activity

don't make "Y" capital here...just copy/paste...

**Comment by arshadansari27** [comment]
It looks bad... with Y being small.. really...

**Comment by YunusDange** [comment]
but it is presentation wise incorrect......replace it now...i will take a call on this by showing it to all if it looks bad....but this is looking odd.....coz
