### ISSUE TITLE
Adventures - Backend Issue (No field for Location) 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#190]
I just got that...there is no field to enter Location in Adventure Page Backend..

Out entire filtering depends on 2 things 1) Activity & 2) Location

although we have a field to enter activity but there is not field to enter Location

Please add that asap

**Comment by arshadansari27** [comment]
It is not present inside the edit page, it is present as a link on the list-view in the adventure table.. to the most right.. Its called Set Location link.. That is how I could do at the moment.. so use that for now....

**Comment by YunusDange** [comment]
cool...it will work
