### ISSUE TITLE
Homepage - Members Button

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#191]
Linked it properly....due to URl changes....it gets affected

**Comment by arshadansari27** [comment]
didn't understand!!

**Comment by arshadansari27** [comment]
Refresh the page.. press F5, if urls are not changing... it could be due to cached page...

**Comment by YunusDange** [comment]
Checked that......even open the website in private window ...but that link was attached to previous URL..
once i click on that URL..it takes me to 
http://fitrangi.com/community/profile

**Comment by arshadansari27** [comment]
u mean members button on top... didnt realize u meant that...

**Comment by YunusDange** [comment]
yes .....that button
