### ISSUE TITLE
Discussion - Latest Post Should be First Structure 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#197]
One thing we have forgot to include in discussion section... that is "Latest Post Should be First Structure"
Our discussion section is nothing but a forum and i have been through many forums and one IMPORTANT functionality forums has is.....it always work in a way where latest post comes first and it follows though out

for eg.
let's take below image 
![screenshot 2015-05-27 12 10 47](https://cloud.githubusercontent.com/assets/7126709/7830305/7c2c450e-0469-11e5-8707-cb706bab83e8.png)

Here Your (Arshad's) Post is 3rd ....but if some one write any comment (reply) to your post then that will come to first place before yuni fitrangi (my post)....
now let's say someone commented on the last post that is "Where can you do paragliding in India" then it will become first post and Your post become second and Yuni Fitrangi post become third..

This will go on as per the latest comment and reply..

THIS IS ONE OF THE MAIN FUNCTIONALITY FOR WHICH FORUMS ARE USED....users keep commenting on posts so that there post should be seen on main page....Have to apply this functionality here

**Comment by YunusDange** [comment]
I don't think it's working...i have commented on 2 post but there position is still same....they should come 1st and 2nd as per the comment


http://www.fitrangi.com/discussion/where-can-i-do-paragliding-in-india--

http://www.fitrangi.com/discussion/what-are-the-best-monsoon-trek-destinations-near-mumbai-

**Comment by arshadansari27** [comment]
once this is closed, test it by adding a new post to one of the contents to see if it comes to the top
