### ISSUE TITLE
Some Bugs related to "Favorites" button 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#20]
When i add some organisers to ‘Favorites’ then it should appear in his section as well that someone have Favourated it , which is missing right now (he may not have follower & following section, instead a changed name section like ‘Favourited By’).

Also the button name should be "Add to Favorites" instead if just "Favorites".

**Comment by armashfankar** [comment]
we are still pending with this issue .

**Comment by YunusDange** [comment]
This is Still Pending Guys!

**Comment by arshadansari27** [comment]
What is pending here? @armashfankar

**Comment by YunusDange** [comment]
whenever i add some organiser to favorite.....nothing changes in organisers "Favorited By" section...please check that

**Comment by armashfankar** [comment]
modal is ready..but we are not able to fetch data for  in organisers "Favorited By" section.
Its coming Blank
