### ISSUE TITLE
Finder : Search Bar Text is not visible

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#201]
At Finder Section....."Search by Name" text is not visible

![screenshot-2015-05-30-15 25 33](https://cloud.githubusercontent.com/assets/7126709/7896733/dac95a42-06e0-11e5-9a04-784be5eab20f.jpg)

**Comment by arshadansari27** [comment]
Its a browser problem.. will take a bit of time to fix..

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
It is not a Browser Problem 
Remove class="p-20" from the input it will work fine in all browser

**Comment by arshadansari27** [comment]
thanks man

**Comment by armashfankar** [comment]
done!
