### ISSUE TITLE
"Create Business Profile" Form Issues

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#202]
1) No Field to upload Logo (Profile Image) 

2) Whenever User missed any field then a error message come.....but "OK" button is not visible....it is only visible on mouse over....  but it has to be visible throughout
![screenshot-2015-05-30-15 25 33](https://cloud.githubusercontent.com/assets/7126709/7896709/60a3e44e-06e0-11e5-87ba-228cc504861d.jpg)

3) Why the guiding text is missing for " Youtube & Linkedin URL" like for Facebook it is written "Enter facebook Url" etc..
![screenshot-2015-05-30-15 32 43](https://cloud.githubusercontent.com/assets/7126709/7896745/5465e9c4-06e1-11e5-9994-8f7fdf4b67e1.jpg)

4) When User received a message saving that profile is created and awaiting admin approval...then why it is visible in "Finder" section ....it has to be visible and workable only after Admin Approval...

**Comment by arshadansari27** [comment]
1) you can only upload logo once the profile is created.. there's a backend issue which is why we had to do it this way....  we will improvise in time
2) this is #204 
3) I'm fixing

**Comment by YunusDange** [comment]
1) Okkz.....it is very critical...first of all remove that Default image from Form (default logo/profile image) and then there should be some way we should inform user from where he can upload the logo image

4) ???
