### ISSUE TITLE
"Business Profile" View & Structure Issues

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#203]
1) Change the word for Business profile from "FAVOURITE ACTIVITIES :" to "SPECIALIZED ACTIVITIES :"
as this is a business profile....
![screenshot-2015-05-30-15 39 37](https://cloud.githubusercontent.com/assets/7126709/7896763/7b19e90c-06e2-11e5-8859-bc60128d8591.jpg)

2) We have taken Address of the business..it has to be Visible somewhere

3) BIGGEST ISSUE is TAB's 
Business profile should not have TAB's like 
ADVENTURES DONE & MY WISHLIST 
(Also this functionality should be inactive for business profile...like adding any Adventure to his ADVENTURES DONE or  MY WISHLIST)

4) We will have other TAB called "OFFERINGS" in future where all his offerings will come (just keep this in mind)

**Comment by YunusDange** [comment]
no need for "City/region & Zipcode" to be shown as a content....it is already visible in Location area of that business profile..
see below
![screenshot-2015-05-30-17 19 49](https://cloud.githubusercontent.com/assets/7126709/7897170/57e55986-06f0-11e5-9995-ab39081a4cff.jpg)

**Comment by YunusDange** [comment]
Also this buttons on thumbnails are visible to business profile and it is also working ...?
![screenshot-2015-05-30-17 29 42](https://cloud.githubusercontent.com/assets/7126709/7897227/909eb2da-06f1-11e5-8601-4b99fd9e28f3.jpg)

**Comment by YunusDange** [comment]
Also this buttons on thumbnails are visible to business profile and it is also working ...

![909eb2da-06f1-11e5-8601-4b99fd9e28f3](https://cloud.githubusercontent.com/assets/7126709/7897667/5194b21e-0701-11e5-814d-e03c3f720d0a.jpg)

**Comment by arshadansari27** [comment]
create a separate issue specific to that and keep this closed

**Comment by arshadansari27** [comment]
No need to create a separate issue for this one.. however, next time on wards create separate issues different points... that allows me to keep history of changes clean.. I'll know what I changed per issue.. If multiple issues, or points are covered in the same issue, over time it gets difficult to differentiate the changes... This is especially important for those who will join development later.. they should be able to search closed issues and research to help them solve problems... so each issue should be as specific as possible...

**Comment by YunusDange** [comment]
Okkz...sure
