### ISSUE TITLE
"Business Profile" Admin Backend Missing Fields 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#205]
Following fields are missing When you edit OR create Business Profile through Admin 

Means...This Fields are available while Filling a Form as a user while creating any business profile but missing when it comes to admin approval OR When Admin try to create business profile directly from Dashboard

1) Office Adress

2) City/State/Country

3) Pincode /Zipcode

4) Select your Speacialities (Activity)

**Comment by arshadansari27** [comment]
2) City/State and Country is location thing which is not on the form, cause its geo complete thing.. so I have the same thing done here like it is for adventures and old profiles.. you can view and set location from the listing itself, instead of the detail editor...

**Comment by arshadansari27** [comment]
Also, specialities are reference to activities as well as text, cause we need to keep those activities too in which they specialize but we don't have a page yet.. The string values of those we don't have in our own activities are listed in the form.. but the references are a bit tricky to get there... this shall be a sperate issue to be handled separately...

**Comment by YunusDange** [comment]
I doesn't understand your last comment....so please create a separate ticket for this from your side...mentioning what's exactly the error is
