### ISSUE TITLE
"Business Profile" - Hide Chat/Message Functionality while "Awaiting Approval" 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#208]
This is one of the main trick we have to do to keep Business profile in good standing...
As Initially 90% of business profile will be created by us and we will start coordinating with businesses to give them access so what i suggest is below:

Hide the Send Message button till the profile is "Awaiting Approval" 
![screenshot-2015-05-31-10 46 03](https://cloud.githubusercontent.com/assets/7126709/7900649/62d00dd6-0782-11e5-9a1e-46a00eee7a93.jpg)

The reason behind is.... till the profile is not handed over to the concern party no user should able to send messages to this business profiles as they will not receive any reply (which may harm that business profiles reputation).
So if we keep it HIde then this issue will solve and also in case user created a business profile & it comes for admin approval ...then same procedure will be there. which will make more sense

**Comment by arshadansari27** [comment]
I'm also removing the button follow, coz it doesn't makes sense to allow users to follow, til we approve the profile...

**Comment by YunusDange** [comment]
Don't remove FOLLOW button...coz there are many uses of that like below

1) people would like to follow nearby operators or gear dealers to keep them in there list..specially as a information

2) there is a posibility that many users know particular operator and they follow and even inform that operators about there present on fitrangi 

3) if a particular business profile has good number of followers without getting approval from our side then he may want to get access of that account etc..etc

So Keep the Follow button

**Comment by arshadansari27** [comment]
The follow is there.. not showing till approval...
besides, that button alone looks too bad... so it serves the purpose of only allowing followers to come once it is approved

**Comment by YunusDange** [comment]
I think...little bit formatting issues can be handled as it is a business profile....
coz if we keep follow button Hide..then we have to hide other buttons (sections) showing Number of followers and following as in this case ....they are looking weired....

I say this because there is a possibility that many Business profile will remain "Un Approved" for more than 2-3 months...and in this case there has to be some functionality which should be active for them

**Comment by arshadansari27** [comment]
Ohk... I will show follow.... later on even that can help us prioritize the approval process
