### ISSUE TITLE
"Business Profile" - Switch User Functionality Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#209]
1) Following is the main issue before Switching from USER to BUSINESS profile there is only one option which is understandable but after switching there comes 3 options to switch back to user which is very confusing and which is not needed ...

The Option should be simple with one option only:
before:  Switch to "Business Name"
after:     Switch to "User name"

![screenshot-2015-05-31-10 55 19](https://cloud.githubusercontent.com/assets/7126709/7900717/6a3867a6-0784-11e5-90b7-37ec8f67a0f4.jpg)
  
That's it

2) BTW switching option is not working :) in the present case also ...so after changes check whether they are switching properly..

If there is anything to explain or discuss...call me directly...:)

**Comment by arshadansari27** [comment]
Not able to recreate the issue.. i'm sending a fix.. test and let me know if it works...

**Comment by YunusDange** [comment]
Switch Functionality is working now

but why Business profile have 2 options (parents and all)
![screenshot-2015-05-31-15 53 06](https://cloud.githubusercontent.com/assets/7126709/7901587/4ff3c042-07ad-11e5-9f4b-7ba754835a85.jpg)

Make it simple by giving just one option....coz if user switched to business profile then the only switching option he should have is Switch to User again. 
Like the option he has when he is using personal profile like below
![screenshot-2015-05-31-10 57 06](https://cloud.githubusercontent.com/assets/7126709/7901595/98084c36-07ad-11e5-9252-97cf5ac690e9.jpg)

ONE OPTION TO SWITCH IN BOTH THE CASES..will make it simple to operate....no need to give parent and child making facility etc.

**Comment by arshadansari27** [comment]
i removed it.. let me check

**Comment by arshadansari27** [comment]
Check if this is fixed.. I can't recreate this scenario on my machine.. on my machine it works exactly as you want it to work :8ball:

**Comment by YunusDange** [comment]
FIXED Now....i am closing this
