### ISSUE TITLE
Homepage - Cover Image Replacement

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#210]
the cover image we have right now is not looking proper in mobile version due to sunset in the middle...in mobile version it comes in the center and content over it ...is not visible properly...

so i have edited the images little bit which i think will solve this issue...

Updated the same in dropbox.....please check and replace it

**Comment by arshadansari27** [comment]
is it saved in the same place with the name home-banner.jpg?

**Comment by YunusDange** [comment]
Yes!
