### ISSUE TITLE
"Business Profile" - "CLAIM THIS LISTING" button concept

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#212]
right now what is happening is we are creating many business profiles from Admin and then connecting with owners to give them access but in normal senario what will happen is....user will directly come to site and after seeing his company listing..he will want to take charge of that.....so there should be some way for this

we can't create a complicated structure for that now...i have the following plan...

1) right now we have button called "Awaiting Approval" on the business profile listed by user
![screenshot-2015-05-31-10 46 03](https://cloud.githubusercontent.com/assets/7126709/7906503/ec8928c4-0849-11e5-8dde-4ff29b40bf0f.jpg)

We can use the same button differently at different condition like below

1) Present condition where user had submitted a business listing then this button should read like ""Awaiting Approval" (THIS IS WORKING PROPER FOR NOW...as there is always a manager assign to it...who have created this listing/profile...we just need to approve it)

2) Let;s Say if we have added a business profile through Admin which means there is no Manager assign to it then this button should read "CLAIM THIS LISTING" which should be click-able...
after clicking on this button a Pop-Up window should come on which we can put a guiding text like How user can claim this listing"

This will be more practical

**Comment by arshadansari27** [comment]
This and the feedback form and the report not ok are part of the same functionality.. they are messages from user to admin so they need appropriate backend.. I cannot create a feature on a whim.. this is a correct idea and needs to be implemented correctly... it will take a bit of time..

**Comment by YunusDange** [comment]
Okkz

**Comment by YunusDange** [comment]
Arshad, we need to make this priority...as i can start adding B2B profiles...only when this functionality is there...and we have to start this to get more traction

**Comment by YunusDange** [comment]
How it is solved..? where is the functionality ;)

this is one if the business profile i have added...there is no functionality to CLAIM THIS
http://www.fitrangi.com/profile/the-skyonars

**Comment by arshadansari27** [comment]
This is solved to the manual extent... 
Here is how it works... When u create a business profile, you have to mark it as admin approved. Coz u put it there.
Secondly, there should be no one in the 'managed by' field, only then any one can claim this. Once you assign managed by from admin, it is difficult to make it empty. So, I'm not able to show this on the-skyonars profile. However, try another profile and do the following things: 
1. Is Business Profile : true
2. Admin Approved: true
3. Managed By : empty

Then you will see claim this profile button on the profile page and if some one has already claimed it, then there will be 'claimed' button (disabled) shown there, saying its already been claimed. So when you put the claimer in managed by field, the 'claimed' button will also disappear and it will function normally.

**Comment by arshadansari27** [comment]
I'm keeping it opened till you test it and then you if there is still trouble, put it here. I will fix it or you can close it, if its working ok.

**Comment by YunusDange** [comment]
It's working but have following issues

1) Change button name from "CLAIM LISTING" to "CLAIM THIS LISTING"

2) When Someone is Claiming this without LOGIN then a Popup box comes saying .."Please Login before making request"...but that box doesn't say till i read that message...it disappear in a second...

So keep that box till user click on OK button or else...rather than OK give a "LOGIN" button instead.which will make more sense
Also that text should read "Please Login to send this request".

3) When Someone is Claiming this WITH LOGIN then a Popup box comes and disappears and text message comes....
So Either keep the Popup Box OR Direct text message...not both

Also that text should read 
"Info! Thank you for claiming this Listing. Admin will connect with you to approve it"

**Comment by arshadansari27** [comment]
Test this... i think it shd work now

**Comment by YunusDange** [comment]
It's working but find another bug :)

Let's say someone claimed it and i added that person as a manager to that profile,,,but then i remove him from manager...or 
lets say Admin accidentally added someone as a manager to particular business profile 
and then when i try to delete that manager.....to make that profile induvidual (means to activate claiming option agian).

IT IS NOT HAPPENING 
see
http://www.fitrangi.com/profile/outdoortravelgear-com

i have added Yuni Fitrangi as a Manager to his ...just to check...but now i want to delink both and want this profile to be available for claiming...CAN'T THAt...please try

**Comment by arshadansari27** [comment]
Make a different ticket... its another backend problem. I m having tough
time figuring out why it cant be removed.
