### ISSUE TITLE
Footer Menu's - Pages creation

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#213]
We have created a Content for Footer Menu's like
About | Contribute | Advertise | Privacy | Terms etc.

let me know how to go ahead..

I suggest it will be good if we can create a separate pages for all this ...and make editing links for those pages available to Admin (in Administration )...coz this content will changes many time...withing next 1-2 month....so i can do that changes from my end

ONE MORE THIS 
for About Page....we have created info-graphic content like zomato ( https://www.zomato.com/about )
Let me know what you thing about this? and whether the images can be placed similarly in the content?

**Comment by arshadansari27** [comment]
i saw the info graphic in dropbox.. i don't see the content.. You can put the content there.. we can merge some of the content in single page and keep some in a separate page. Or we can create a single page for all of them and make sure the link goes to that particular section of the page.. just like home page we can have all the topics above on the same page as sections.. The content (eg Terms) which has huge size can have its container with inner scroll so the page height is not too long... let me know what you think

**Comment by YunusDange** [comment]
I think for now let's have a separate page for all of them......looking at the scope of our website... we will need separate page for all in future....so let's make seperate pages from now onwards...we will keep on improving on it

i will upload the content of all the pages till today evening...we you can copy paste on the website

**Comment by arshadansari27** [comment]
I have added the pages.. Do not change the name field... that is how I'm linking the pages....

**Comment by YunusDange** [comment]
How to change this cover image text
![screenshot-2015-06-05-09 55 19](https://cloud.githubusercontent.com/assets/7126709/7999474/34340276-0b69-11e5-898b-b78be5eb6204.jpg)

every section may need different text on cover image
OR
can we remove this cover image from all sections (footer menu's) coz there is no need of cover images in this section.......also it will look different section where people will only visit if they want to know about us

**Comment by arshadansari27** [comment]
I'll remove the banner image section completely.. so we will have title at top directly

**Comment by YunusDange** [comment]
Yup...that would be better
