### ISSUE TITLE
Activity Page - Do's & Don'ts Content Color Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#214]
Have a look at this 
![screenshot-2015-06-01-13 40 38](https://cloud.githubusercontent.com/assets/7126709/7908598/fe1719f6-0863-11e5-92b4-fadeb42731e3.jpg)

OR visit any activity page....
the Content of Do's and Don'ts section is not readable properly....i doesn't have any access to make it proper

So Make the content color black or dark gray...so that it can be readable

**Comment by arshadansari27** [comment]
will do
