### ISSUE TITLE
"Business Profile" - Approval Structure "Unique" Issue 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#218]
Check this.....this are the last 6 Profiles i received in "Approvals > Business profiles"
![screenshot-2015-06-04-17 25 29](https://cloud.githubusercontent.com/assets/7126709/7983525/dac100ca-0ade-11e5-8772-184cb6464d40.jpg)

Coincidently this are the same last 6 user registrations we had received as well....so i am very much sure..that they have not created any business profile....so i think this is some bug due to which i am receiving this profiles in Approval (which is created for Business profiles)

**Comment by arshadansari27** [comment]
ill look into that
