### ISSUE TITLE
My Page - Profile Images are stretched 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#219]
![screenshot-2015-06-05-10 51 09](https://cloud.githubusercontent.com/assets/7126709/7999945/682db45c-0b71-11e5-9472-ebcab0fc91b2.jpg)

issues received from user

profile image is still stretched.. ...no user will like if his image is not looking proper....need to solve this

**Comment by arshadansari27** [comment]
I need to create an image cropper for profile image.. coz that will be real fix for this problem...

**Comment by YunusDange** [comment]
I am creating a separate ticket for image cropper...so that it will be remembered
