### ISSUE TITLE
"Business Profile" - Links are not clickable

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#220]
See this...This links are not click-able 
![screenshot-2015-06-05-14 44 13](https://cloud.githubusercontent.com/assets/7126709/8003044/b1c548da-0b91-11e5-90e1-dbb90f5073ed.jpg)

1) Make it clickable...
2)  the link should be open in new window (so that user will not leave our website)

ONE SUGGESTION
for social media links...can we just show Icon's linked with the URL submitted by profile creator.
coz right now entire social media link is visible which is not looking proper ...also at some place the link is too big which distrubs the UI

**Comment by arshadansari27** [comment]
the suggestion is what i was thinking....

**Comment by YunusDange** [comment]
Still 4 issues are there

1) email address is linked...remove that linking

2) website address is not linked....Linked this ..(it should open in new window)

3) Twitter icon is missing....add that after Facebook (order should be Facebook, Twitter, Google+, Linkedin & Youtube)

4)Remove RSS icon...there is no need for this
![screenshot-2015-06-05-18 35 39](https://cloud.githubusercontent.com/assets/7126709/8006501/34cdb396-0bb2-11e5-8d37-39482641bb89.jpg)

**Comment by arshadansari27** [comment]
Rss if for blog.. if the guy has a blog, i didn't find any better to put there.. can u find a better alternative ?

**Comment by YunusDange** [comment]
we want user to bring his blogpost to Fitrangi....not sending users from
fitrangi to his blogpost

and which alternative ?

On Fri, Jun 5, 2015 at 7:35 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Rss if for blog.. if the guy has a blog, i didn't find any better to put
> there.. can u find a better alternative ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/220#issuecomment-109303787>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
Still the user would want to see his blog being listed if he gives that to us

**Comment by YunusDange** [comment]
we can hide it for now and if i receive any feedback on this then we can think over it...THIS IS A B2B USER..... i am not seeing anyone will have any problem with it....coz that is a main thing...we want user to bring his blogpost to Fitrangi

**Comment by YunusDange** [comment]
1) email address is linked...remove that linking .???????????????

2) website address is not linked....Linked this ..(it should open in new window)?????????????????

**Comment by arshadansari27** [comment]
it is linked...

**Comment by YunusDange** [comment]
It is linked now.....
but the link is not taking users towards that website 
please click and check on below profile (website link of user)

http://www.fitrangi.com/profile/stepin-adventure
http://www.fitrangi.com/profile/green-valley-resort

**Comment by YunusDange** [comment]
Not Solved....check the links.....
http://www.fitrangi.com/profile/stepin-adventure
http://www.fitrangi.com/profile/green-valley-resort

after clicking on there web address the diverted link comes as
http://www.fitrangi.com/profile/sikkimuttareygreenvalleyresort.blogspot.com
http://www.fitrangi.com/profile/www.stepinadventure.com
