### ISSUE TITLE
Error Message from GOOGLE ANALYTICS

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#221]
One Error Message received from GOOGLE ANALYTICS

Any solution for this

Redundant Hostnames
"Property Fitrangi.com is receiving data from redundant hostnames. Some of the redundant hostnames are:

    fitrangi.com
    www.fitrangi.com

Redundant hostnames are counted as separate rows in reports, so hits that are going to the same page on your site from different hostnames will be split into multiple rows. With data split across multiple rows, traffic to specific pages will appear lower than it actually is.

To avoid this problem, consider setting up a 301 redirect from one of your redundant hostnames to the other, or create a search-and-replace filter that strips "www." from hostnames."

**Comment by arshadansari27** [comment]
fixed
