### ISSUE TITLE
"Journal" to "Blog"

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#227]
There is one critical change we have to do that is converting "Journal" section name to "Blog"

There is lot of confusion between users to understand the concept of journal for now...as journal basically means a collection of articles, blogs and lot more....where our journal section dosen't have that much content right now...

secondly..we want people to write for us...so it basically comes under blog...journal basically means the curated content we provide...

thirdly , there are users who doesn't go to Journal section thinking that..there will be some gyaan....some people even told me that...you dosen't have a blog section? means they have not visited the journal.....so means We are wrong in putting this name for now....NEED TO MAKE IT EASY AND SIMPLE

FOLLOWING CHANGES HAS TO BE DONE 

1) Menu: 
Change "Journal" to "Blog"

2) URL
http://www.fitrangi.com/journals
to 
http://www.fitrangi.com/blogs

3) Homepage Section
"Popular Journals"
to 
"Popular from Blog"

4) Homepage Cover Image Statistics 
18 Journals
to
18 Blogs

**Comment by arshadansari27** [comment]
Lets call these things articles... instead of blog...

**Comment by YunusDange** [comment]
No....Don't call it Articles...we want users to write for us..so Blog is most suitable...and Articles always looks like a gyaan...our main focus is to inspired others by sharing experiences....we are just writing artciles from our site so that content will be more useful

So Keep it BLOG

**Comment by YunusDange** [comment]
at 1) Menu: it should be "BLOG" and not Blogs...remove the "S"

2) one mistake from my side URL Should be 
http://www.fitrangi.com/blog        
remove the "S"

3) Homepage Section
"Popular Journals"
to 
"Popular from Blog"

4) Homepage Cover Image Statistics 
18 Journals
to
"18 Blog Post"

**Comment by arshadansari27** [comment]
1 3 and 4 are easy peasy...
2 is a bit difficult, so next time whenever work is related to urls, let's make sure that its not changed multiple times...

**Comment by YunusDange** [comment]
Yup...right
