### ISSUE TITLE
Activity Facet not working.

### ISSUE THREAD

**Issue by armashfankar** [arshadansari27/fitranginew#23]
When we try to open activities using "facet" it shows "There seems to be insufficient information about the data to create filters."
There is a problem with filters in ACTIVITY parts

**Comment by arshadansari27** [comment]
This requires a change in facet system that we currently have and it is a very tough thing to change.. just like it was difficult to put date time filter in facets. I have to take a week atleast to fix this. So I will focus on finishing the remaing before coming to this. Although this is high priority

**Comment by arshadansari27** [comment]
fixed
