### ISSUE TITLE
Business Profile's manged_by cannot be emptied once any value is entered in it.

### ISSUE THREAD

**Issue by arshadansari27** [arshadansari27/fitranginew#232]
Unable to empty managed_by field from admin_panel, what gives?

**Comment by arshadansari27** [comment]
This will take some time. I dont' see any error message so I don't know what is wrong. I have a feeling, that its a bug in the framework. I will have to dive deep. 

As for the work around for this problem. I have put in a system would show 'Claim this Listing' even when admin user is managing it. So all the profiles you create, even if it has you as managed_by will be available for claiming.

I think we should just leave it at this, as of now. what do you think?

**Comment by YunusDange** [comment]
Perfect...i think the problem is solved then.....i am closing this ticket for now
