### ISSUE TITLE
My Stream - Images Looks Pixelate 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#236]
Images posted on "My Stream" by any user looks pixelate even if original image quality is proper

see below

![screenshot 2015-06-08 12 19 51](https://cloud.githubusercontent.com/assets/7126709/8029298/05ad8d42-0dd9-11e5-8742-4d653428d4ec.png)

![screenshot 2015-06-08 12 19 50](https://cloud.githubusercontent.com/assets/7126709/8029294/ec2954aa-0dd8-11e5-8a08-63b4e5946085.png)

**Comment by armashfankar** [comment]
done!!
