### ISSUE TITLE
Business profile - Profile Image issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#238]
See this
![screenshot-2015-06-08-15 50 16](https://cloud.githubusercontent.com/assets/7126709/8032750/4311def0-0df6-11e5-9566-88685d7931ee.jpg)

profile images are looking transparent....i know they may have uploaded .PNG files (it is uploaded by user)....but is there any solution for this??

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 

add white bcakground color for profile pic thru css like 
for example(.profile img{background-color:#ffffff;})
if jpg pic uploaded so you will see correct pic & if png there will be white bg image.

**Comment by arshadansari27** [comment]
ill try this today

**Comment by armashfankar** [comment]
done
