### ISSUE TITLE
"Forget Password" option in not there

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#24]
We doesn't have a forget "password option" on website. Please add that as soon as possible.

**Comment by arshadansari27** [comment]
I will not be pushing this change on live, coz there is no point in giving forgot password option, till we add notification.

**Comment by YunusDange** [comment]
Okkz, thats right. let's try to have Notification functionality ASAP. as our most of the features requires that right now, as we have already started receiving questions in the forum, so whenever they get answers , they should get notification through Mail & on website as well.

**Comment by YunusDange** [comment]
Forget Password Option Should be Active Now....As So Notification functionality should be in place

**Comment by armashfankar** [comment]
Forgot Password is done @YunusDange sir.
Please check its working with email functionality
