### ISSUE TITLE
What is RSS feed? Is it required?

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#245]
Like to know more about it....what exactly RSS feed work and whether we should have it for our website?

**Comment by arshadansari27** [comment]
Its not important for us... Since we want users to not just read from our site but also interact and form community, which won't happen if RSS is there.. Using RSS people will stay away from site and use google reader or feedly to get updated content on site. Its good from pure content site..

**Comment by arshadansari27** [comment]
We wont be publishing RSS feeds for now.. May be later for all our
discussion and content. But its bad business if we want them on site.

However, we will use other's rss feed to steal their content and bring it
on our site. :)
With their permission ofcourse. So it wont be stealing from users, but
their content platforms.

**Comment by YunusDange** [comment]
Cool...i am talking in that perspective as well..bringing others content on our site..for now we can keep it closed
