### ISSUE TITLE
Can we add More Ad's ?

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#26]
Right now i can only add 3 ad's in the right side widget , whenever i add 4th ad, it dosen't shows in the ad area, Please make it 6 (so that we can add 6 tabs as ad's)

**Comment by arshadansari27** [comment]
@armashfankar @musab95 

Change from the ModelView to return 6 objects instead of 3.. Test with many adverts on different pages.

**Comment by YunusDange** [comment]
Still Pending

**Comment by arshadansari27** [comment]
Test this by adding more advertisements to the site. Also make sure you select INTERNAL as the placement option. So that they can show up.

**Comment by YunusDange** [comment]
Done...It's Working Now

On Fri, Feb 27, 2015 at 12:56 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Test this by adding more advertisements to the site. Also make sure you
> select INTERNAL as the placement option. So that they can show up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/26#issuecomment-76350157>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
