### ISSUE TITLE
Essy Option for uploading Profile Picture

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#27]
Right now uploading a profile picture is a task & thats why we have only 8-9 profile pictures out of 40 users we have on fitrangi. so we have to make it simple......
1st is login with Fb & G+ solves the problem .
2nd is like a normal method where user just have to click on thumbnail of Profile picture to upload new profile picture like other site has.

**Comment by arshadansari27** [comment]
Upload part is done. Social login based image importing remains.
