### ISSUE TITLE
Social Sharing Issue 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#29]
1) Whenever i Share any article on Social Media (Facebook) The Article topic is not visible , instead "Fitrangi.com | India's Complete Adventure Portal" Is visible. Check by Posting some article Links in Facebook to understand the issue or CALL ME

2) We need to add Social Sharing buttons on each content ...so that people can directly share it on Social Media

**Comment by arshadansari27** [comment]
@armashfankar the change is in jinja template for pount 1. base template contains title... we can use title block... 
for point 2.. lets find if there is an existing js plugin.

**Comment by armashfankar** [comment]
This is also done with proper links and title.

**Comment by YunusDange** [comment]
Done ,
