### ISSUE TITLE
Mail Notifications

### ISSUE THREAD

**Issue by arshadansari27** [arshadansari27/fitranginew#3]
In order of priority

1) Admins to be mailed for different activities like subscription
2) User to be notified in case as follows:
    a) Subscribed with us
    b) Registered
    c) Article/Comments Posted by him/her
    d) Received Comments on articles posted by him/her

**Comment by armashfankar** [comment]
b)
Dear ABC,
Welcome to Fitrangi.com, your one-step destination for all your adventurous needs. We are happy to have you as the newest member of our Adventure Sports Community.
 
Here are your login credentials.
Username:	talktoarmash@gmail.com
Password:	XYZ1234

Regards
Team Fitrangi

**Comment by arshadansari27** [comment]
I have added the notification system and it needs some fine tuning..  Please start testing.. 
@armashfankar @musab95 There is a notification folder inside templates directory that contains the mail message with little bit of jinja.. We can do the work here to improve mail design as well as update the content. So please connect with yunus and decide which mail template is ok and what needs to be changed.

**Comment by armashfankar** [comment]
ok

**Comment by arshadansari27** [comment]
@armashfankar the absolute path shudnt contain /app before /asset

**Comment by armashfankar** [comment]
Changes are done for Absolute path.
