### ISSUE TITLE
Customise URL's for each Content (Articles, Destinations & Activities)

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#30]
right now we have some Id's in each content type.....if we can have a a option for customizing the URL then i can start customizing it  whenever i plan to share some content on Social Media.... It will look  more professional & related OR else on social media it looks like a SPAM Link.

Also An Option to add summery in each content type with SEO Enable perspective.

**Comment by arshadansari27** [comment]
Done for all the content and profiles
