### ISSUE TITLE
** FORUM Improvements

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#32]
1) Replace the Tagline from “POST YOUR QUESTIONS HERE” to “ADD YOUR DISCUSSION TOPIC HERE”

2) Keep the tag’s Clickable (So that it can filter the Forum Posts accordingly – That’s the Use)

3) Every Post Should show the Number of Replies it gets on the Main Forum Post Itself.

4) Option to Insert IMAGE and VIDEO in Question & Answers (Very Important – As we are also planning to post all the ATConclave Videos on the website for discussion)

**Comment by arshadansari27** [comment]
Marking closed.. created seperate tickets for remaining ones

https://github.com/arshadansari27/fitranginew/issues/38

https://github.com/arshadansari27/fitranginew/issues/39
