### ISSUE TITLE
** Proper Filter Options in ACTIVITY & DESTINATIONS

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#33]
**ACTIVITY FILTERS
1) Following Should be the Order & Name for the filters , so that it will be easy to understand & follow
     - Land Sports
     - Water Sports
     - Air Sports
     - Snow Sports  
     - Other Sports
     - Travelling and Sightseeing
(To Make all filters look same (dropdown) Divide (Snow Sports Section into two Activity: 1) Skiing 2) Snowboarding)
(If Possible Keep First Filter list open in all the Filter sections to show that it’s a dropdown menu)

**LOCATION FILTERS
1)  Remove Other Countries, Our Focus should be clear to visitors & Show State wise Filters (In all the Sections)

**Comment by arshadansari27** [comment]
This is facet related change that is also part of a bug here: https://github.com/arshadansari27/fitranginew/issues/23

We need to solve the two simeltaneously.

**Comment by arshadansari27** [comment]
Closing
