### ISSUE TITLE
Events (Interesting events) to be enabled.

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#37]
3 things

1st.... right now in "INTERESTING EVENTS" section we can see "8" events....so let's make it "4" . means only one row should be there on homepage....no need for a separate menu for now....keep it as it is...

2nd... Activate it on homepage...right now users can't click on the event ....so make it active now like other sections....I will upload the events once it is active.

3rd....it seems that the section is following a pattern which we have created for uploading events (Trips)....but now when we are using it to just upload some interesting event, the format can be similer ..it can just be a content like blog....so need to create that option while uploading any content

**Comment by arshadansari27** [comment]
Cover all types of events,
exhibitions,
trips 
conclave
meetups
with their respective content type handling

**Comment by YunusDange** [comment]
Only Trips can be separate.... will not mix it with other events...but
yes.in backend the structure will looks the same as mentioned

On Fri, Feb 27, 2015 at 3:39 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Cover all types of events,
> exhibitions,
> trips
> conclave
> meetups
> with their respective content type handling
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/37#issuecomment-76368857>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
Right now, let's keep em all together.. and not add them.

**Comment by YunusDange** [comment]
Sure.. Just change the Filters Name
It should be

- Adventure Trips
- Conference, Seminars & Workshops
- Events & Exhibitions
- Competitions

On Sat, Feb 28, 2015 at 7:14 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Right now, let's keep em all together.. and not add them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/37#issuecomment-76526601>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
