### ISSUE TITLE
IMAGE and VIDEO in Question & Answers

### ISSUE THREAD

**Issue by arshadansari27** [arshadansari27/fitranginew#39]
This could be in forum or it could be seperate media channel?

**Comment by YunusDange** [comment]
It will be best if this option is available in Forum itself....As we are using it for discussion rather than Q&A... Discussion need all features related to content

**Comment by arshadansari27** [comment]
That makes sense and discussion would also be more engaging after that..

**Comment by arshadansari27** [comment]
We can now add videos in place of cover image and those will show. However, for q & a, this needs to be handled differently. We need a UI design to lock on before this feature can be enabled. Feature is already in, just enabling remains
