### ISSUE TITLE
URGENT: Advertisments Final 2 Corrections

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#43]
1) Remove the Name coming with black strip...proper image should be visible ...details can be seen on mouse over

2) Homepage Footer Ad: Ad a word "Advertisement" on the Left side above the ad (small font like inner ad space)

**Comment by arshadansari27** [comment]
@armashfankar @musab95  Although this is done, it can be improved a bit from UI perspective

**Comment by arshadansari27** [comment]
Closing for now till some thing specific crops up
