### ISSUE TITLE
Destination Pages - Proper Formating

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#44]
All the Destination Pages Needed proper formatting. First Table is missing in all the Pages.(it was converted into a normal content)

I think this will be done once we have that new Dashboard. but we have to this ASAP as this are the pages i used for marketing a lot.

Keep me updated about this. We have to assign this work to someone as it will take a good amount of time

**Comment by arshadansari27** [comment]
This wont be a ticket here.. All the content must be curated and edited to loook better with formatting. this needs to be handled as curator task, not to be on github
