### ISSUE TITLE
Proper Struture to Call Related Data in Each Content Type

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#45]
We have to create proper channel & facet structure to Call Related Data in Each Content Type. Very Critical

**Comment by arshadansari27** [comment]
Related list is already being looked up by the content having same facet. this needs to be handled differently when we focus on related content. So closing this for now.. This will come up with the new thought by this saturday, however, it will be more specific then. right now, closing this will clean up tickets and help focus more on urgent stuff
