### ISSUE TITLE
Advertisement URL's should open in new Window

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#46]
Now, whenever i click on any advertisement, it takes me to the advertisers website in the same window. User should not leave Fitrangi.com , so the advertisement has to open in new window & not in the same window

**Comment by armashfankar** [comment]
Done.

**Comment by arshadansari27** [comment]
You have not pushed the code yet?

**Comment by armashfankar** [comment]
Just now pushed ..was out

**Comment by arshadansari27** [comment]
@YunusDange test and close

**Comment by arshadansari27** [comment]
tested and closing
