### ISSUE TITLE
Problem with alignment of photos and images

### ISSUE THREAD

**Issue by armashfankar** [arshadansari27/fitranginew#58]
@89abdul as i told you that you have created cards for images and photos it is for perfect square images and what images we have are not perfctly squared,So please design a card where image of any size can be automatically adjusted.

**Comment by 89abdul** [comment]
@armashfankar attach screenshot of the screens on which page would you like to create.

**Comment by 89abdul** [comment]
@armashfankar updated your my-style.css from dropbox
uploaded the css with changes.
reply if any more changes
