### ISSUE TITLE
Activity Icon's - Not able to change image

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#62]
There is option in every activity called "ICON's" however i upload the image but nothing changes on the actual page of that activity. default image is there
Please check

**Comment by arshadansari27** [comment]
icon image is hard coded at the moment... so whichever image is not ok, i will update it myself.. so i'll keep this open where you can put the ones that are not ok...

**Comment by YunusDange** [comment]
Nothing urgent in that...just want to make more attractive icons ...that
can be done lateron..
Just mentioned it coz in backend there is a option for inserting icons
which is not working..
