### ISSUE TITLE
Adventures - No Info Page is Visible

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#65]
We have added 4 Adventures (Info Page)
but it is not visible on the main page (http://beta.fitrangi.com/explore/adventure)
although you can see the uploaded Adventures in back end
 please have a look...

The same is with Discussions ...we have 3 discussions added but nothing is visible in discussion section as well as other areas where it is supposed to be visible.

***NOTE: both the things are approved through admin ...so that is not a problem

**Comment by arshadansari27** [comment]
I believe this is fixed..
