### ISSUE TITLE
Can't upload profile Image

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#68]
I have tried uploading a profile image for my user account (it is not connected with Google or Facebook...direct login account) but after following the steps still the image dosen;t show as my profile image...instead a default image is visible...

please check the issue

**Comment by arshadansari27** [comment]
Can you guys test this? It works for me.....

**Comment by YunusDange** [comment]
It's still not working for me..

It works with social logins but when you create a account with direct email
id and password then manually uploading the profile image is not working

On Thu, Apr 30, 2015 at 12:14 AM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Can you guys test this? It works for me.....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/68#issuecomment-97536872>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
