### ISSUE TITLE
BACKEND: Discussion - Keep it simple (4 things only)

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#70]
Discussion functionality will be like blog but for users it should not act like a blog ...it should look like a discussion only....so backend should be minimal and simple like below..take only 4 things from user

1) Title:
2) Main Content: (here user can upload Image or Video in the content itself if he wants....coz most the discussions will be a plain text...so dont make images and videos compulsory here) 
3) Cover Image: (it should be optional...and also mention somewhere that it is optional....if user dosen't 
upload any image then the discussion will use our default image ...we will create a special image for this)
4) Tag's:
 and then Save option

**Comment by arshadansari27** [comment]
Please test it.. Its fixed...

**Comment by YunusDange** [comment]
Insert Cover Image option is placed 2nd and it's compulsory...it's creating lot's of confusion

Placed it 3rd & write a heading for it as "Cover Image (Optional)"

the structure should be like below:
1) Title:
2) Main Content: 
3) Cover Image (Optional): 
4) Tag's:
and then Save option

**Comment by arshadansari27** [comment]
Should i follow the same layout for article? except there wil be additional fields and the cover image will not be optional... Or we can make it optional and use a set of randomly chosen images as cover images if users do not use one.. they can also replace it if they don't like our choice? what do you think?

**Comment by YunusDange** [comment]
- No..ARTICLE layout is different & it is perfect for now....coz cover image is compulsory for articles & other options make it different from discussion

- This change is only for Discussions layout as per it's use and need

- here in discussion, Cover image option should be last & Optional And yes, we can use a set of randomly chosen images as cover images if users do not use one...yes, they can replace it if they don't like our choice..fine with it

**Comment by YunusDange** [comment]
"Add a discussion" button is not working....
