### ISSUE TITLE
Featured Discussions Widget is Missing

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#76]
for eg. go to below discussion page
http://beta.fitrangi.com/discussion/discussion-1-for-testing-purpose

you will see a widget to show "featured discussion" at right side...but now you can see recent articles there in place of Discussions ....so rectify that

also limit the number of featured discussions that can be shown at that area as per the UI

**Comment by arshadansari27** [comment]
I think this is fixed now.. but the view is not correct.. i'll try to fix that....
