### ISSUE TITLE
Adventure Grid View

### ISSUE THREAD

**Issue by arshadansari27** [arshadansari27/fitranginew#78]
Adventure grid view title, if it is long, it makes the grid view longer in height and causes the following grid view of adventure to skip some space in between. We need to make the height fixed.

**Comment by arshadansari27** [comment]
This should be taken care of for all the grid views.. We can do this like we did in previous fitrangi site.. Place them vertically instead of horizontally.. so the varying sizes will not have any problem of missing spaces.... Check www.fitrangi.com for example in any search view....

**Comment by YunusDange** [comment]
@arshadansari27 
Adventures Section Thumbnail boxes=> whenever title goes for two lines... there is bottom empty space. causing the structure...

i think this is the same issue for which this ticket has open..( IF NOT, THEN PLEASE CREATE A SEPARATE TICKET FOR THIS)
