### ISSUE TITLE
SEO Integration

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#8]
This is one of the cirtical area we have to work on...not that Urgent..
Fitrangi is a content oriented website and most of our audience come from google search, we should have strong SEO (Search Engine Optimisation) & Customise URL's which go hand in hand with SEO. i have done a good research on SEO so i can help in this...our earlier website is SEO friendly and mostly come on fist page of google in most search results...it's a long term process but we have to focus on it from start, so that we can get the results after 4-5 months

**Comment by arshadansari27** [comment]
Removed the custom ur part, since we have already accomplished that.
