### ISSUE TITLE
Homepage Slide Image Sizing Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#80]
Homepage Slide Image is not looking proper in desktop....i think it is due to size of the image...
for eg. check slide image of Discussion http://beta.fitrangi.com/community/discussion
It is looking proper in all the devices (laptop, desktop, ipad etc) end to end....
homepage slide images should also look the same

**Let me know if there is any size issue....i will give you a image of exact size (let me know that exact size as well

**SAME PROBLEM IS THERE FOR OTHER TWO SECTIONS
1) ADVENTURES
2) FINDER

**Comment by arshadansari27** [comment]
Are you talking about the banner image? if not then send screenshots..

**Comment by YunusDange** [comment]
Yes banner Image .... see the screen shot
![screenshot-2015-04-30-18 03 11](https://cloud.githubusercontent.com/assets/7126709/7412728/48e8c642-ef63-11e4-8ffa-d386f704fa56.jpg)
