### ISSUE TITLE
Locations Library need to added ASAP

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#81]
Locations Library need to added ASAP...as it is required in all the sections and it is the SECOND Important filter after Activity in all the sections....so it should also be tested properly

**Comment by arshadansari27** [comment]
I think I can leave that you to add locations through the location under admin first and then select them from adventures, trips and events

**Comment by YunusDange** [comment]
The Only Problem it has right now is.....Users can't enter there location while creating/editing there profile.....our UI structure shows Users location everwhere , so it is important ....so i think Location library will work better in this case....what say..?

**Comment by arshadansari27** [comment]
in case of users the location library is being used
.. the drop down isnt showing... due to UI issues... but when you hit enter after typing location in edit profile, it gets nearest match from maps... will fix drop down issue with help from @89abdul

**Comment by YunusDange** [comment]
Okkz...means for other things i have to insert Locations manually under
Admin....right,,,??

On Fri, May 1, 2015 at 2:01 AM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> in case of users the location library is being used
> .. the drop down isnt showing... due to UI issues... but when you hit
> enter after typing location in edit profile, it gets nearest match from
> maps... will fix drop down issue with help from @89abdul
> <https://github.com/89abdul>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/81#issuecomment-97956799>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
yes...

**Comment by YunusDange** [comment]
Still not able to add new locations from tools menu

**Comment by arshadansari27** [comment]
ill check...

**Comment by YunusDange** [comment]
I can add locations now.....but now it dosnen't ask to select State (as it selects the entire address with that city & sate together which is good, entering state's seperately section is anyway deleted now) but it is affecting the filtration as users can't filter just by typing/selecting state (which should be available)

any solution for this?

**Comment by arshadansari27** [comment]
there is a solution based on geocode.. but right now they dont have that
option to search by state anyway

**Comment by YunusDange** [comment]
Okkz...See if there is any solution for this as filtration through states is must

**Comment by arshadansari27** [comment]
if it is a must, where are we asking that question from user? Coz the locations we ask in filters simple show the locations we already have.. if that needs to be a state wise filteration, a lot of changes will need to go, so I'm not sure how will we solve that without changing functionality.. It is either the current way or completely the stateway...

**Comment by YunusDange** [comment]
It was there in our first version....
keep it aside for now...we will think over it later On....

On Sat, May 9, 2015 at 2:37 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> if it is a must, where are we asking that question from user? Coz the
> locations we ask in filters simple show the locations we already have.. if
> that needs to be a state wise filteration, a lot of changes will need to
> go, so I'm not sure how will we solve that without changing functionality..
> It is either the current way or completely the stateway...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/81#issuecomment-100454229>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
closing this ticket... move it to the word file for now... we need less open tickets to stay focussed
