### ISSUE TITLE
"Upcoming Trips" Menu's - Make it visible 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#84]
"Upcoming Trips" Menu's
1) Upcoming Trips

right now keep only 1 menu but soon we will be adding following menu's 

2) Camp Sites 
3) Adventure Parks & Resorts
4) Logistics & Travel

**Comment by arshadansari27** [comment]
Is this the submenu under upcoming trips?

**Comment by YunusDange** [comment]
Yes....Submenu Under Upcoming Trips!

**Comment by arshadansari27** [comment]
so let's add this when we have a mechanism to attach trips to one of the given categories.. right now the functionality isn't there in backend.. so let's not add a new menu for now..

**Comment by arshadansari27** [comment]
if it is needed, we will reopen it later or create new..
