### ISSUE TITLE
Journal - Top Blogs TAB Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#85]
Journal - Top Blogs TAB

when i visit this TAB without login to my account ...it is showing the Top Blogs properly as per the UI....BUT when i visit this TAB (with Login ) then this TAB looks same like MY BLOGS Tab...with all those features (Edit, Delete & Publish option). Please have a look

**Comment by arshadansari27** [comment]
Are those articles created by you? if yes then it will show like that... The blogs you added will have the same view as my blogs view..

My blog shows only your blogs.... when logged in..
Top blog shows all blogs but yours are given different actions.... when logged in

My blog show nothing ... when not logged in
Top blog shows everything normally .. when not logged...

Check that and let's decide on what to keep as final....

**Comment by YunusDange** [comment]
Okkz...got this

But i think...Top blog should show everything normally with and without login.....like the homepage of Journal ...as it shows statistics like Number of Comments & Number of Views (this functionality is yet to be added..can be done afterwords) , so user will like to see the same for his/her blogs ....as he is anyway getting editing & other options in My blogs...so no need to give that here....what say!?

**Comment by arshadansari27** [comment]
We can show all of it in every view so users won't have to enter edit mode to see how many comments or views did they get.... it will be shown differently for my blogs and rest of the blogs... but will be shown...so closing this and considering the views to be shown as part of the functionality of showing number of comments and views
