### ISSUE TITLE
SignIn Popup Window Changes - Make it even simpler 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#88]
Make this Structure Should be like Register Popup window ….eg.
Email Id….Password….remember me….forget password….Sign In button ...Register button & Close button ….AND in next line…Social Media Login Icon’s

See the reference image attached 
![screenshot-2015-04-30-17 23 39](https://cloud.githubusercontent.com/assets/7126709/7412672/b7e15f38-ef62-11e4-966e-0f0d4ad0fda8.jpg)

**Comment by arshadansari27** [comment]
why like this? I really dont' see the problem with current one.. help me see it...

**Comment by YunusDange** [comment]
just trying to make it more simpler ....as got this inputs from a UX guy

1) Normal Login & Social Logins should look two different things...so it should be divided
2) Sign in button color is similar to Twitter...so for sometime it create confusion...so matching it to our theme
3) user should get register link from here itself if he is not register..rather than searching for it..

it will make things more simpler ...nothing else

**Comment by 89abdul** [comment]
check this out for sign in & register ref
we have to make like this





-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --
[image: photo]
ABDUL RAZAK SHAIKH
 CREATIVE   dESIGNER
Mobile:9819992152 | Email:89abdul@gmail.com
<https://www.facebook.com/89abdul>  <https://twitter.com/89abdulrazak>
<https://www.linkedin.com/in/89abdulrazak>
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
we can make 1 induvidual new page for login & register some ref like this check this link below
http://www.universalhunt.com/
http://www.universalhunt.com/login.php
https://about.me/
https://adventure.com/register/?redirect_to=http://adventure.com/login/?redirect_to=http://adventure.com/

No Modal Pop up.
I have got 1 error in modal popup When we concentrate on modal popup then we get that error.

1. When we click on button for modal popup the modal box comes slowly stuck in header & after a second we see the modal content.
2. A user who have slow internet can't see the modal content. 


![untitled-1](https://cloud.githubusercontent.com/assets/8382087/7446376/0a7c03ea-f1f4-11e4-82d6-00e873a517f7.jpg)

**Comment by arshadansari27** [comment]
@abdul
.. lets make a separate page to do both

**Comment by YunusDange** [comment]
Cool...!

**Comment by 89abdul** [comment]
ok





-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --
[image: photo]
ABDUL RAZAK SHAIKH
 CREATIVE   dESIGNER
Mobile:9819992152 | Email:89abdul@gmail.com
<https://www.facebook.com/89abdul>  <https://twitter.com/89abdulrazak>
<https://www.linkedin.com/in/89abdulrazak>
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- -- -- --

**Comment by arshadansari27** [comment]
@89abdul any updates for this page?

**Comment by 89abdul** [comment]
give me some time for this page i'll make for both register & login

**Comment by 89abdul** [comment]
@arshadansari27 @YunusDange 
Sign in & Register Page is Uploaded in Dropbox with My-style.css & banner image also 

1 thing you have to check now 
for login & register page banner style has been changed.
check my-style.css for more information that style is included. line-4649 to 4662
