### ISSUE TITLE
Add New Menu : Videos

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#9]
Actually we have decided to create this section later but we are getting some request to list there videos on our website . so it will be great if we can create one more section called Videos (menu) where we caan call all our Youtube channel videos. so that whenever we add new video on our Youtube channel , it should automatically come on our website video section.
Possible??

**Comment by YunusDange** [comment]
I think.....it's time to introduce this....

**Comment by YunusDange** [comment]
Hello Arshad,
I understand the Streams now......Video Section is different!

It is same like Articles & Destination Section with same kind of Filtering options , The Only Difference is the content will be Auido - Video which will be directly Fetched from our Channel OR Manually add by us. Let's Add this Section now.

**Comment by arshadansari27** [comment]
Is this different from Forum postings? I dn't see the need for this if that is already available in discussions

**Comment by YunusDange** [comment]
Yes.........Video Section is different!

It is same like Articles & Destination Section with same kind of Filtering options , The Only Difference is the content will be Auido - Video which will be directly Fetched from our Channel OR Manually add by us. Let's Add this Section now.

**Comment by arshadansari27** [comment]
Right now there is no video section, but each content can have youtube videos instead of the cover image. We simply need to put the video id from the url and put it in the editor view, under youtube embed.
