### ISSUE TITLE
Upcoming Events…View All button is stretched in size…make it normal

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#91]
Upcoming Events…View All button is stretched in size…make it normal

**Comment by arshadansari27** [comment]
we need to reach at least 6 events, it is the only solution for now.. I and @89abdul will sit together soon, to fix UI specific bugs..

**Comment by YunusDange** [comment]
Okkz ...got it..
will do that and then close it from my end

On Fri, May 1, 2015 at 5:54 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> we need to reach at least 6 events, it is the only solution for now.. I
> and @89abdul <https://github.com/89abdul> will sit together soon, to fix
> UI specific bugs..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/91#issuecomment-98122310>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by YunusDange** [comment]
Sorry....i dnt think we will be having six events at a time anytime soon....so can you make it 3??

means only 3 events will be visible on homepage and others will be on main page.
 So adjust the button Stretch accordingly . 

Let me know

**Comment by arshadansari27** [comment]
Will need Abdul @89abdul 's help on this.. so assigning to him...
