### ISSUE TITLE
Activity Page - Discussions TAB Functionality 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#94]
Discussion Section… should be define properly…there should be a option while writing any Discussion to select a related activity …so that particular discussion can come in related Activity Section...

**Comment by arshadansari27** [comment]
This is acheived by adding a tag with the name of activity.. It will automatically show up in activity tab.. The auto complete may not be showing all activity names.. that I can take care of....

**Comment by YunusDange** [comment]
Cool...Close it once the Auto Complete Functionality works here as i have
tried adding tag's manually and it needs to be correct spelling wise as
well as Capital and Small word wise etc......which is difficult to get
correct evertime..

but it's working...that's good

On Fri, May 1, 2015 at 6:29 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> This is acheived by adding a tag with the name of activity.. It will
> automatically show up in activity tab.. The auto complete may not be
> showing all activity names.. that I can take care of....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/94#issuecomment-98128218>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
