### ISSUE TITLE
Adventures - Thumbnail Icon’s ( DONE THIS & ADD TO WISHLIST) should work properly

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#96]
Thumbnail Icon’s ( DONE THIS & ADD TO WISHLIST) should work properly…right now it is not working….It should directly add entries to users done this & add to wish list area without opening the Info page .

**Comment by arshadansari27** [comment]
I don't understand this one.. I put this comment before from phone, but some how it didn't get posted... Here it is again...

**Comment by YunusDange** [comment]
need to talk on this...i will explain it to you tomorrow over phone....keep it open..
