### ISSUE TITLE
Adventures - Thumbnail Icon’s ( DONE THIS & ADD TO WISHLIST) should be similar to Inner Icon’s

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#97]
Thumbnail Icon’s ( DONE THIS & ADD TO WISHLIST) should be similar to Inner Icon’s OR else we can create a special Icon’s to be used which can easily replicate this

**Comment by arshadansari27** [comment]
didnt understand this... u can put details here or have a call on this one...reassigning

**Comment by YunusDange** [comment]
Let's have a call on this today....ping me once you wake up

On Fri, May 1, 2015 at 1:57 AM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Assigned #97 <https://github.com/arshadansari27/fitranginew/issues/97> to
> @YunusDange <https://github.com/YunusDange>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/97#event-294471275>.
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*
