### ISSUE TITLE
Register as Organization flow "Create Business Profile"

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#99]
“Add Organisation”  Button is missing… refer the UI design ….we have to created a structure for adding business profiles through this button.

**Comment by arshadansari27** [comment]
I would like to suggest 'Become an organization' rather than adding it... coz users will have to be already logged in... so they ask that their profile to be converted to business... lemme know what you think..

If u don't think this is correct idea, then i don't really understand how 'add organization' will work.

**Comment by YunusDange** [comment]
I think it will not work in this way....coz users will not become organisers
as organisers profiles need some extra info as suggested in UI...

so we can create a profile for them once they submit there info through "Add
Organisation" button which will have a seperate login and act as a
profile....

need to discuss this and figure it out how it will work actually.....Let me
create a proper structure for this .... will talk to you with
proper explanation of how it will work

On Fri, May 1, 2015 at 3:23 PM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> I would like to suggest 'Become an organization' rather than adding it...
> coz users will have to be already logged in... so they ask that their
> profile to be converted to business... lemme know what you think..
>
> If u don't think this is correct idea, then i don't really understand how
> 'add organization' will work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/99#issuecomment-98087022>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by arshadansari27** [comment]
Just to be correct here, since we have create business profile button on the top, I will add the button inside finder too with the same exact functionality for top button? and since we already have top button shown for every user (unless they already have a business profile that they are managing), then what is the need for this separate button.

**Comment by YunusDange** [comment]
This is just to push Users to create business profile....After some time Finder will be used to search about different operators and gear dealers and when any business owner is on that page and see so many business profile ....that button will grab his attention and he may create his business profile as well.... It more of a push marketing strategy...

ONE IMPORTANT THING IS ...I just have a look at the Form....there are many fields are missing....means the information we need from users to create any particular business profile..

REFER BELOW STRUCTURE (we are created earlier ....we need this inputs from users to create any business profile)

![add-organiser-page](https://cloud.githubusercontent.com/assets/7126709/7743647/63675922-ffba-11e4-9636-a49af09b2893.jpg)

**Comment by arshadansari27** [comment]
I am assigning this to @89abdul 

Its a seperate page all together that we dont have UI for yet.... 

@89abdul we need to talk about this... before you start making this one....

**Comment by YunusDange** [comment]
Okkz... @89abdul  it's little urgent...need to make it perfect before launch

**Comment by arshadansari27** [comment]
@89abdul You don't have to design this exactly as it is shown.. especially try to use the whole page and cover all those things in same order.. no need for the side advertisement space, etc.. take ur best judgement...
